# Reverse Generation Tool Version 3.0
name = "Tailwind Syntax"
primary = "@blue"
theme = "dark"


# Theme Colors
[color]
red = "#F87171" # Constants
yellow = "@red..h+40"
green = "@blue..h-60"
teal = "#99f6e4" # built-ins
blue = "#7DD3FC" # Strings
purple = "#6366F1" # Primary
pink = "#F472B6" # Keywords
black = "#1E293B" # Background
grey = "#CBD5E1" # Attributes
grey2 = "#94A3B8" # Comments
grey3 = "#64748B" # Operators
white = "#FFF" # Text
white2 = "#e5e7eb" # Cursor

[background]
code = "$background.secondary"
drop_target = "$background.bars.topbar"
gutter = "$background.primary"
panel = "$background.bars.topbar"
primary = "@black"
secondary = "$background.primary"
surface = "$background.primary"
terminal = "$background.primary"

[background.bars]
bottombar = "$background.bars.topbar"
# scrollbar = "background.bars.scrollbar"
scrollbar_thumb = "@grey3..50"
toolbar = "$background.primary"
topbar = "@black..v-0"

[background.bars.tabbar]
background = "#29344900"
active = "$background.primary"
inactive = "$background.primary"

[border]
primary = "#32405350"
code = "$self.primary"
disabled = "$self.primary"
scrollbar = "$self.primary"
secondary = "$self.primary"
selected = "$self.primary"
transparent = "$self.primary"

[button]
active = "$button.primary"
disabled = "$foreground.inactive"
primary = "$primary..50"
selected = "$self.primary..v+5"
hover = "$button.primary..v-5"

[code.error]
border = "@red"
foreground = "@red"

[code.info]
border = "@blue"
foreground = "@grey3"

[code.hint]
border = "@teal"
foreground = "@teal"

[code.warning]
border = "@yellow"
foreground = "@yellow"

[cursor]
background = "$background.primary..v+15"
highlighted = "$cursor.background"
line = "#0000"
match = "$background.primary..v+8"
primary = "@white2"
search = "@yellow..60"
selection = "$self.match..(a.80, v+10)"
spaces = "#0000"

[element]
active = "$self.selected..v-5"
disabled = "element.disabled"
hover = "$self.selected..v+5"
primary = "element.primary"
selected = "$background.primary..v+5"

[foreground]
hover = "@white..20"
inactive = "@blue..(a.ff, v-45)"
link = "@blue"
placeholder = "@grey2"
primary = "@white"
secondary = "@white2..v-10"
code = "$background.primary..v+40"

[foreground.linenumber]
active = "@grey2"
inactive = "@grey3"

[git.created]
background = "@green"
border = "$border.primary"
foreground = "@green"

[git.ignored]
background = "$background.primary"
border = "$border.primary"
foreground = "$foreground.inactive"

[git.modified]
foreground = "@yellow"

[indent]
active = "@grey3"
inactive = "@grey3..80"
multi = [
	"@red..50",
	"@yellow..50",
	"@green..50",
	"@blue..50",
	"@teal..50",
	"@pink..50",
	"@purple..50",
	"@grey..50",
]

[scheme]
black = "@white"
blue = "@blue"
cyan = "@teal"
pink = "@pink"
green = "@green"
red = "@red"
white = "@white"
yellow = "@yellow"
black2 = "$self.black..v-15"
black3 = "$self.black..v-25"
blue2 = "$self.blue..v-15"
blue3 = "$self.blue..v-25"
cyan2 = "$self.cyan..v-15"
cyan3 = "$self.cyan..v-25"
green2 = "$self.green..v-15"
green3 = "$self.green..v-25"
pink2 = "$self.pink..v-15"
pink3 = "$self.pink..v-25"
red2 = "$self.red..v-15"
red3 = "$self.red..v-25"
white2 = "$self.white..v-15"
white3 = "$self.white..v-25"
yellow2 = "$self.yellow..v-15"
yellow3 = "$self.yellow..v-25"

[syntax.attribute]
color = "@grey"

[syntax.boolean]
color = "@red"

[syntax.builtin]
color = "$syntax.attribute.color"

[syntax.comment]
color = "@grey3"

[syntax.constant]
color = "@red"

[syntax.doc]
color = "@grey2"

[syntax.function]
color = "@pink"

[syntax.function.builtin]
color = "@teal"

[syntax.hint]
color = "@grey2"

[syntax.keyword]
color = "@grey"

[syntax.link]
style = "@blue"

[syntax.method]
color = "$syntax.function.color"

[syntax.number]
color = "@red"

[syntax.operator]
color = "@grey3"

[syntax.primary]
color = "$primary"

[syntax.property]
color = "@grey"

[syntax.punctuation]
color = "@grey3"

[syntax.punctuation.special]
color = "@grey2"

[syntax.special]
color = "$primary"

[syntax.string]
color = "@blue"

[syntax.tag]
color = "@pink"

[syntax.text]
color = "@white"

[syntax.type]
color = "@pink"

[syntax.variable]
color = "@white"
