# Reverse Generation Tool Version 3.0
name = "Tailwind Syntax"
primary = "@lightskyblue"
theme = "dark"

# Theme Colors
[color]
burlywood = "#F7CA71"
darkgray = "#94A3B8"
darkslategray = "#324053"
darkslategray2 = "#1E293B"
darkslategray8 = "#1D283A"
hotpink = "#F472B6"
lightgray = "#CBD5E1"
lightgreen = "#7CF9A4"
lightskyblue = "#7DD3FC"
paleturquoise = "#99F6E4"
salmon = "#F87171"
slategray = "#64748B"
steelblue = "#437187"
white = "#FFFFFF"

[background]
code = "@darkslategray2"
drop_target = "@darkslategray8"
gutter = "@darkslategray2"
panel = "@darkslategray8"
primary = "@darkslategray2"
secondary = "@darkslategray2"
surface = "@darkslategray2"
terminal = "@darkslategray2"

[background.bars]
bottombar = "@darkslategray8"
scrollbar_thumb = "@slategray..50"
toolbar = "@darkslategray2"
topbar = "@darkslategray8"

[background.bars.tabbar]
active = "@darkslategray2"
background = "#29344900"
inactive = "@darkslategray2"

[border]
code = "@darkslategray..50"
disabled = "@darkslategray..50"
primary = "@darkslategray..50"
scrollbar = "@darkslategray..50"
secondary = "@darkslategray..50"
selected = "@darkslategray..50"
transparent = "@darkslategray..50"

[button]
active = "@lightskyblue..50"
disabled = "@steelblue"
primary = "@lightskyblue..50"
selected = "#7FD6FF50"

[code.error]
background = "@darkslategray2"
border = "@salmon"
foreground = "@salmon"

[code.info]
background = "@darkslategray2"
border = "@lightskyblue"
foreground = "@slategray"

[code.warning]
background = "@darkslategray2"
border = "@burlywood"
foreground = "@burlywood"

[cursor]
background = "#314360"
highlighted = "#314360"
line = "#0000"
match = "#28374F"
primary = "#E5E7EB"
search = "@burlywood..5F"
selection = "#35486880"
spaces = "#0000"

[element]
active = "@darkslategray8"
disabled = "element.disabled"
hover = "#2A3A54"
primary = "element.primary"
selected = "#243147"

[foreground]
code = "#5170A0"
hover = "@white..1F"
inactive = "@steelblue"
link = "@lightskyblue"
placeholder = "@darkgray"
primary = "@white"
secondary = "#CCCED1"

[foreground.linenumber]
active = "@darkgray"
inactive = "@slategray"

[git.created]
background = "@lightgreen"
border = "@darkslategray..50"
foreground = "@lightgreen"

[git.ignored]
background = "@darkslategray2"
border = "@darkslategray..50"
foreground = "@steelblue"

[git.modified]
foreground = "@burlywood"

[indent]
active = "@slategray"
inactive = "@slategray..80"
multi = [
	"@salmon..50",
	"@burlywood..50",
	"@lightgreen..50",
	"@lightskyblue..50",
	"@paleturquoise..50",
	"@hotpink..50",
	"#6366F150",
	"@lightgray..50"
]

[scheme]
black = "@white"
black2 = "#D8D8D8"
black3 = "#BFBFBF"
blue = "@lightskyblue"
blue2 = "#69B2D3"
blue3 = "#5D9CBA"
cyan = "@paleturquoise"
cyan2 = "#82CEBF"
cyan3 = "#72B5A7"
green = "@lightgreen"
green2 = "#69D38B"
green3 = "#5DBA7A"
pink = "@hotpink"
pink2 = "#CC5F99"
pink3 = "#B25386"
red = "@salmon"
red2 = "#D16060"
red3 = "#B75454"
white = "@white"
white2 = "#D8D8D8"
white3 = "#BFBFBF"
yellow = "@burlywood"
yellow2 = "#D1AB60"
yellow3 = "#B79654"

[syntax.attribute]
color = "@lightgray"

[syntax.boolean]
color = "@salmon"

[syntax.builtin]
color = "@lightgray"

[syntax.comment]
color = "@slategray"

[syntax.constant]
color = "@salmon"

[syntax.doc]
color = "@darkgray"

[syntax.enum]
color = "@lightskyblue"

[syntax.function]
color = "@hotpink"

[syntax.function.builtin]
color = "@paleturquoise"

[syntax.hint]
color = "@darkgray"

[syntax.keyword]
color = "@lightgray"

[syntax.lifetime]
color = "@lightskyblue"

[syntax.method]
color = "@hotpink"

[syntax.number]
color = "@salmon"

[syntax.operator]
color = "@slategray"

[syntax.primary]
color = "@lightskyblue"

[syntax.property]
color = "@lightgray"

[syntax.punctuation]
color = "@slategray"

[syntax.punctuation.arrow]
color = "@slategray"

[syntax.punctuation.bracket]
color = "@slategray"

[syntax.punctuation.delimiter]
color = "@slategray"

[syntax.punctuation.special]
color = "@darkgray"

[syntax.punctuation.symbol]
color = "@darkgray"

[syntax.special]
color = "@lightskyblue"

[syntax.string]
color = "@lightskyblue"

[syntax.string.regex]
color = "@lightskyblue"

[syntax.string.special]
color = "@lightskyblue"

[syntax.tag]
color = "@hotpink"

[syntax.text]
color = "@white"

[syntax.type]
color = "@hotpink"

[syntax.variable]
color = "@white"

[syntax.variable.parameter]
color = "@white"

[syntax.variable.special]
color = "@lightskyblue"

# Overrides
[overrides]
"name" = "tailwind-syntax"
"themes/0/style/syntax/string.escape/color" = "@lightskyblue"

# Deletions
[deletions]
keys = [
]
