# Reverse Generation Tool Version 3.0
name = "Yue Eclipse NEW 2"
primary = "@lemonchiffon"
theme = "dark"

# Theme Colors
[color]
black = "#000000"
darkgray = "#999999"
gainsboro = "#DFDFDF"
hotpink = "#FF91A6"
lemonchiffon = "#FFF5C2"
lightblue = "#B6C6FF"
lightcyan = "#CEFFFF"
lightgoldenrodyellow = "#E2FFCC"
pink = "#F9BEF0"
pink2 = "#FFB7E0"
white = "#FFFFFF"

[background]
drop_target = "@pink..22"
gutter = "@black..03"
panel = "@black..00"
primary = "@black..03"
secondary = "@pink..33"
surface = "@black..EB"
terminal = "@black..03"

[background.bars]
bottombar = "@black..F0"
scrollbar_thumb = "@white..40"
toolbar = "@black..03"
topbar = "@black..EB"

[background.bars.tabbar]
active = "@darkgray..1F"
background = "@black..00"
inactive = "@black..00"

[border]
disabled = "@pink..33"
primary = "@pink..33"
scrollbar = "@darkgray..6E"
secondary = "@darkgray"
transparent = "@pink..33"

[button]
active = "@pink..12"
primary = "@pink..33"
selected = "@black..EB"

[code.error]
background = "@black..EB"
border = "@hotpink"
foreground = "@hotpink"

[code.info]
background = "@black..EB"
border = "@lightblue"
foreground = "@lightblue"

[code.warning]
background = "@black..EB"
border = "@lemonchiffon"
foreground = "@lemonchiffon"

[cursor]
background = "@black..EB"
line = "@white..10"
match = "@lemonchiffon..1F"
primary = "@gainsboro"
search = "@lemonchiffon..39"
selection = "@white..1F"

[element]
hover = "@gainsboro..22"
selected = "@lemonchiffon..1F"

[foreground]
hover = "@pink..12"
link = "@lemonchiffon"
secondary = "#9A9A9A"

[foreground.linenumber]
active = "@gainsboro"
inactive = "#7B7B7B"

[git.created]
foreground = "@lightgoldenrodyellow"

[git.ignored]
foreground = "#4F4F4F"

[git.modified]
foreground = "@lemonchiffon"

[guide]
active = "@pink..33"

[icon]
accent = "@lemonchiffon"

[scheme]
black = "@black..EB"
black2 = "@darkgray"
blue = "#969696"
blue2 = "@black..EB"
cyan = "@lightcyan"
green = "@lightgoldenrodyellow"
red = "@hotpink"
red2 = "@hotpink"
white = "@gainsboro"
yellow = "@lemonchiffon"
yellow3 = "@lemonchiffon"

[syntax.boolean]
color = "@lightcyan"

[syntax.builtin]
color = "@lightcyan"

[syntax.comment]
color = "#7B7B7B"

[syntax.constant]
color = "@lightcyan"

[syntax.constructor]
color = "@lightcyan"

[syntax.doc]
color = "@lemonchiffon"

[syntax.escape]
color = "@lightcyan"

[syntax.function]
color = "@lightgoldenrodyellow"

[syntax.keyword]
color = "@pink"

[syntax.method]
color = "@lightgoldenrodyellow"

[syntax.number]
color = "@pink2"

[syntax.operator]
color = "#FFCAB3"

[syntax.primary]
color = "@lemonchiffon"

[syntax.punctuation]
color = "@pink2"

[syntax.punctuation.bracket]
color = "@pink2"

[syntax.punctuation.delimiter]
color = "@pink2"

[syntax.punctuation.special]
color = "@pink2"

[syntax.punctuation.symbol]
color = "@pink2"

[syntax.special]
color = "@lightgoldenrodyellow"

[syntax.string]
color = "@lemonchiffon"

[syntax.string.regex]
color = "@lemonchiffon"

[syntax.string.special]
color = "@lemonchiffon"

[syntax.tag]
color = "@lightcyan"

[syntax.text]
color = "@lemonchiffon"

[syntax.type]
color = "@lightcyan"

[syntax.variable]
color = "@gainsboro"

[syntax.variable.parameter]
color = "@gainsboro"

[syntax.variable.special]
color = "@lightcyan"

# Overrides
[overrides]
"style/background.appearance" = "blurred"
"style/hidden.background" = "$none"
"style/players/2" = { background = "$none", cursor = "$none", selection = "$none" }
"style/players/3" = { background = "$none", cursor = "$none", selection = "$none" }
"style/players/4" = { background = "$none", cursor = "$none", selection = "$none" }
"style/players/5" = { background = "$none", cursor = "$none", selection = "$none" }
"style/players/6" = { background = "$none", cursor = "$none", selection = "$none" }
"style/players/7" = { background = "$none", cursor = "$none", selection = "$none" }
"style/predictive.background" = "$none"
"style/unreachable.background" = "$none"
"style/scrollbar.track.background" = "@black..00"
"style/background" = "@black..EB"
"style/elevated_surface.background" = "@black..F0"
"style/border" = "@black..00"
"style/scrollbar.thumb.border" = "$none"
"style/border.selected" = "@pink..33"
"style/link_text.hover" = "$none"
"style/text" = "#F0F0F0"
"style/terminal.ansi.blue" = "@lightblue"
"style/terminal.ansi.bright_blue" = "$none"
"style/hint.border" = "@lightblue"
"style/success" = "$none"
"style/conflict" = "$none"
"style/conflict.background" = "$none"
"style/deleted.border" = "@hotpink"
"style/modified.border" = "$none"
"style/syntax/function.builtin/color" = "@lightgoldenrodyellow"
"style/syntax/title/color" = "$none"
"style/syntax/number/color" = "#CCB3FF"
"style/syntax/type.super/color" = "@lightcyan"

# Deletions
[deletions]
keys = [
	"/style/accents",
	"/style/editor.indent_guide",
	"/style/editor.indent_guide_active",
	"/style/syntax/attribute/background_color",
	"/style/syntax/boolean/background_color",
	"/style/syntax/comment.doc/background_color",
	"/style/syntax/comment/background_color",
	"/style/syntax/constant.builtin/background_color",
	"/style/syntax/constant.character/background_color",
	"/style/syntax/constant/background_color",
	"/style/syntax/constructor/background_color",
	"/style/syntax/embedded/background_color",
	"/style/syntax/emphasis.strong/background_color",
	"/style/syntax/emphasis/background_color",
	"/style/syntax/enum/background_color",
	"/style/syntax/escape/background_color",
	"/style/syntax/function.builtin/background_color",
	"/style/syntax/function.definition/background_color",
	"/style/syntax/function.method/background_color",
	"/style/syntax/function.special.definition/background_color",
	"/style/syntax/function.special/background_color",
	"/style/syntax/function/background_color",
	"/style/syntax/hint/background_color",
	"/style/syntax/keyword/background_color",
	"/style/syntax/label/background_color",
	"/style/syntax/lifetime/background_color",
	"/style/syntax/link_text/background_color",
	"/style/syntax/link_uri/background_color",
	"/style/syntax/number/background_color",
	"/style/syntax/operator/background_color",
	"/style/syntax/predictive/background_color",
	"/style/syntax/preproc/background_color",
	"/style/syntax/primary/background_color",
	"/style/syntax/property.json_key/background_color",
	"/style/syntax/property/background_color",
	"/style/syntax/punctuation.bracket/background_color",
	"/style/syntax/punctuation.delimiter/background_color",
	"/style/syntax/punctuation.list_marker/background_color",
	"/style/syntax/punctuation.special.symbol/background_color",
	"/style/syntax/punctuation.special/background_color",
	"/style/syntax/punctuation/background_color",
	"/style/syntax/string.doc/background_color",
	"/style/syntax/string.escape/background_color",
	"/style/syntax/string.regex/background_color",
	"/style/syntax/string.special.symbol/background_color",
	"/style/syntax/string.special/background_color",
	"/style/syntax/string/background_color",
	"/style/syntax/tag/background_color",
	"/style/syntax/text.literal/background_color",
	"/style/syntax/title/background_color",
	"/style/syntax/type.builtin/background_color",
	"/style/syntax/type.interface/background_color",
	"/style/syntax/type.super/background_color",
	"/style/syntax/type/background_color",
	"/style/syntax/variable.member/background_color",
	"/style/syntax/variable.parameter/background_color",
	"/style/syntax/variable.special/background_color",
	"/style/syntax/variable/background_color",
	"/style/syntax/variant/background_color"
]
