# Reverse Generation Tool Version 3.0
name = "Ember Neon"
theme = "dark"

# Theme Colors
[color]
antiquewhite2 = "#F4E8DC"
black = "#0C0C14"
black3 = "#101019"
black5 = "#191826"
burlywood = "#F4C592"
burlywood2 = "#FFB999"
cornflowerblue = "#4C87FF"
cornflowerblue2 = "#4CC0FF"
darkslategray = "#515151"
deeppink = "#FF2188"
lightgreen = "#6EDD6E"
mediumpurple = "#B587FF"
sandybrown = "#FFCC4C"
violet = "#E565FF"

[background]
code = "@black3"
gutter = "@black"
panel = "@black"
primary = "@black"
secondary = "@black"
surface = "@black"
terminal = "@burlywood..00"

[background.bars]
bottombar = "#09080F"
scrollbar = "@black..00"
scrollbar_thumb = "@black5..8F"
toolbar = "@black3"
topbar = "@black"

[background.bars.tabbar]
active = "@black3"
background = "@black"
inactive = "@black"

[border]
primary = "#100F1E"
secondary = "@black"

[button]
primary = "#0A0A0F"

[code.error]
background = "@black3"
border = "@deeppink"
foreground = "@deeppink"

[code.info]
background = "@black3"
border = "@cornflowerblue"
foreground = "#5959A3"

[code.warning]
background = "@black3"
border = "@sandybrown"
foreground = "@sandybrown"

[cursor]
background = "@burlywood2"
highlighted = "@black5"
line = "@black5"
match = "#2C2A47E6"
primary = "@burlywood..F0"
search = "#FFFF7F1A"
selection = "#302F469F"
spaces = "@lightgreen..03"

[element]
active = "@black3"
hover = "@black3"
selected = "#1D1D2B"

[foreground]
hover = "#EDEEF0"
primary = "@burlywood..C0"
secondary = "@antiquewhite2"

[foreground.linenumber]
active = "@burlywood..C0"
inactive = "#AAAAAA40"

[git.created]
background = "#E9EFD2BD"
border = "#D7E3AE"
foreground = "#62A35C"

[git.ignored]
background = "#DCDDDE7D"
border = "#CFD1D2"
foreground = "#828A99"

[git.modified]
foreground = "@cornflowerblue"

[indent]
active = "@antiquewhite2..50"
inactive = "@antiquewhite2..1F"
multi = [
	"@cornflowerblue",
	"#C8099D.",
	"@lightgreen",
	"null",
	"@deeppink",
	"@sandybrown",
	"@mediumpurple",
	"@darkslategray",
	"@deeppink",
	"@cornflowerblue",
	"#C8099D.",
	"@lightgreen",
	"null",
	"@sandybrown"
]

[players.2]
background = "#114D777D"
cursor = "#114D77"
selection = "#55B4D33B"

[scheme]
black = "@burlywood..C0"
black2 = "@burlywood..50"
black3 = "@burlywood..50"
blue = "@cornflowerblue"
blue2 = "@cornflowerblue..50"
blue3 = "#C4DAF6"
cyan = "@mediumpurple"
cyan2 = "@mediumpurple..50"
cyan3 = "@mediumpurple"
green = "@lightgreen"
green2 = "@lightgreen..50"
green3 = "@lightgreen..50"
pink = "#C8099D."
pink2 = "#C8099D."
pink3 = "#C8099D."
red = "@deeppink"
red2 = "@deeppink..50"
red3 = "@deeppink"
white = "@darkslategray"
white2 = "@darkslategray..50"
white3 = "@darkslategray"
yellow = "@sandybrown"
yellow2 = "@cornflowerblue"
yellow3 = "@sandybrown"

[syntax.attribute]
color = "@mediumpurple"

[syntax.boolean]
color = "@deeppink"
weight = 700

[syntax.comment]
background = "#FF656B0D"
color = "#FF656BE6"
style = "italic"
weight = 700

[syntax.constant]
background = "@burlywood..0D"
color = "@burlywood..C0"
style = "italic"
weight = 400

[syntax.constructor]
color = "#FF82BC"

[syntax.emphasis]
color = "@deeppink"

[syntax.escape]
background = "@cornflowerblue2..0D"
color = "@lightgreen"
weight = 400

[syntax.function]
background = "@violet..0D"
color = "@violet"

[syntax.hint]
color = "#F00"

[syntax.keyword]
background = "@deeppink..0D"
color = "@deeppink"
weight = 700

[syntax.method]
background = "@violet..0D"
color = "@mediumpurple"
weight = 700

[syntax.number]
color = "@lightgreen"

[syntax.operator]
color = "#FF82BC"
weight = 700

[syntax.property]
color = "@burlywood..C0"

[syntax.punctuation]
color = "#F5E4D1"

[syntax.punctuation.bracket]
color = "#85DBDB"

[syntax.punctuation.delimiter]
color = "#F5E4D1"

[syntax.punctuation.special]
color = "@burlywood..C0"

[syntax.string]
background = "@cornflowerblue2..0D"
color = "@cornflowerblue2"
weight = 400

[syntax.string.regex]
background = "@cornflowerblue2..0D"
color = "@cornflowerblue2"
weight = 400

[syntax.string.special]
background = "@cornflowerblue2..0D"
color = "#0086B3"
weight = 400

[syntax.tag]
color = "@cornflowerblue"
weight = 700

[syntax.text]
color = "@cornflowerblue2"

[syntax.type]
background = "@cornflowerblue..0D"
color = "@cornflowerblue"
weight = 500

[syntax.variable]
background = "@burlywood2..0D"
color = "@burlywood2"

[syntax.variable.special]
background = "@burlywood2..0D"
color = "#A1E5A0"

# Overrides
[overrides]
"style/scrollbar.thumb.hover_background" = "$none"
"style/scrollbar.track.border" = "@black"
"style/border.selected" = "#100F1E"
"style/syntax/comment.doc/color" = "#6591FFE6"
"style/syntax/comment.doc/font_style" = "$none"
"style/syntax/comment.doc/font_weight" = "$none"

# Deletions
[deletions]
keys = [
	"/style/scrollbar.thumb.background",
	"/style/syntax/constant.builtin",
	"/style/syntax/constant.character",
	"/style/syntax/embedded",
	"/style/syntax/enum",
	"/style/syntax/escape",
	"/style/syntax/function.builtin",
	"/style/syntax/function.definition",
	"/style/syntax/function.special",
	"/style/syntax/function.special.definition",
	"/style/syntax/label",
	"/style/syntax/lifetime",
	"/style/syntax/link_text",
	"/style/syntax/link_uri",
	"/style/syntax/preproc",
	"/style/syntax/primary",
	"/style/syntax/property.json_key",
	"/style/syntax/punctuation.special.symbol",
	"/style/syntax/string.doc",
	"/style/syntax/type.builtin",
	"/style/syntax/type.interface",
	"/style/syntax/type.super",
	"/style/syntax/variable.member",
	"/style/syntax/variable.parameter",
	"/style/syntax/variant",
	"/style/title_bar.inactive_background"
]
