# Reverse Generation Tool Version 3.0
name = "Ember Dark"
theme = "dark"

# Theme Colors
[color]
antiquewhite = "#F4E8DC"
black = "#191926"
black2 = "#141320"
burlywood = "#F4C592"
cornflowerblue = "#4C87FF"
cornflowerblue2 = "#4CC0FF"
darkslategray2 = "#515151"
darkslategray3 = "#1F1F30"
deeppink = "#FF2188"
lightgreen = "#6EDD6E"
mediumpurple = "#B587FF"
sandybrown = "#FFCC4C"

[background]
code = "@black"
gutter = "#161623"
panel = "@black2"
primary = "#161623"
secondary = "@black2"
surface = "@black2"
terminal = "@burlywood..00"

[background.bars]
bottombar = "#100F1A"
scrollbar_thumb = "@darkslategray3..8F"
toolbar = "@black"
topbar = "@black2"

[background.bars.tabbar]
active = "@black"
background = "@black2"
inactive = "@black2"

[border]
primary = "#100F1E"
scrollbar = "@black2"
secondary = "@black2"

[button]
primary = "@black"

[code.error]
background = "@black"
border = "@deeppink"
foreground = "@deeppink"

[code.info]
background = "@black"
border = "@cornflowerblue"
foreground = "#5959A3"

[code.warning]
background = "@black"
border = "@sandybrown"
foreground = "@sandybrown"

[cursor]
background = "#FFB999"
highlighted = "@darkslategray3"
line = "@darkslategray3"
match = "#333051E6"
primary = "@burlywood..F0"
search = "#FFFF7F1A"
selection = "#302F469F"
spaces = "@lightgreen..03"

[element]
active = "@black"
hover = "@black"
selected = "#302F46"

[foreground]
hover = "#EDEEF0"
primary = "@burlywood..C0"
secondary = "@antiquewhite"

[foreground.linenumber]
active = "@burlywood..C0"
inactive = "#AAAAAA40"

[git.created]
background = "#E9EFD2BD"
border = "#D7E3AE"
foreground = "#62A35C"

[git.ignored]
background = "#DCDDDE7D"
border = "#CFD1D2"
foreground = "#828A99"

[git.modified]
foreground = "@cornflowerblue"

[indent]
active = "@antiquewhite..50"
inactive = "@antiquewhite..1F"
multi = [
	"@cornflowerblue",
	"#C8099D.",
	"@lightgreen",
	"null",
	"@deeppink",
	"@sandybrown",
	"@mediumpurple",
	"@darkslategray2",
	"@deeppink",
	"@cornflowerblue",
	"#C8099D.",
	"@lightgreen",
	"null",
	"@sandybrown"
]

[players.2]
background = "#114D777D"
cursor = "#114D77"
selection = "#55B4D33B"

[scheme]
black = "@burlywood..C0"
black2 = "@burlywood..50"
black3 = "@burlywood..50"
blue = "@cornflowerblue"
blue2 = "@cornflowerblue..50"
blue3 = "#C4DAF6"
cyan = "@mediumpurple"
cyan2 = "@mediumpurple..50"
cyan3 = "@mediumpurple"
green = "@lightgreen"
green2 = "@lightgreen..50"
green3 = "@lightgreen..50"
pink = "#C8099D."
pink2 = "#C8099D."
pink3 = "#C8099D."
red = "@deeppink"
red2 = "@deeppink..50"
red3 = "@deeppink"
white = "@darkslategray2"
white2 = "@darkslategray2..50"
white3 = "@darkslategray2"
yellow = "@sandybrown"
yellow2 = "@cornflowerblue"
yellow3 = "@sandybrown"

[syntax.attribute]
color = "@mediumpurple"

[syntax.boolean]
color = "@deeppink"
weight = 700

[syntax.comment]
color = "#6591FFE6"

[syntax.constant]
color = "@burlywood..C0"
style = "italic"
weight = 400

[syntax.constructor]
color = "#FF82BC"

[syntax.emphasis]
color = "@deeppink"

[syntax.escape]
color = "@lightgreen"
weight = 400

[syntax.function]
color = "#E565FF"

[syntax.keyword]
color = "@deeppink"
weight = 700

[syntax.method]
color = "@mediumpurple"
weight = 700

[syntax.number]
color = "@lightgreen"

[syntax.operator]
color = "#FF82BC"
weight = 700

[syntax.property]
color = "@burlywood..C0"

[syntax.punctuation]
color = "#F5E4D1"

[syntax.punctuation.bracket]
color = "#85DBDB"

[syntax.punctuation.delimiter]
color = "#F5E4D1"

[syntax.punctuation.special]
color = "@burlywood..C0"

[syntax.string]
color = "@cornflowerblue2"
weight = 400

[syntax.string.regex]
color = "@cornflowerblue2"
weight = 400

[syntax.string.special]
color = "#0086B3"
weight = 400

[syntax.tag]
color = "@cornflowerblue"
weight = 700

[syntax.text]
color = "@cornflowerblue2"

[syntax.type]
color = "@cornflowerblue"
weight = 500

[syntax.variable]
color = "#FFB999"

[syntax.variable.special]
color = "#A1E5A0"

# Overrides
[overrides]
"style/scrollbar.track.background" = "@black2..00"
"style/scrollbar.thumb.border" = "$none"
"style/border.selected" = "#100F1E"
"style/syntax/comment/color" = "#FF656BE6"
"style/syntax/comment/font_style" = "italic"
"style/syntax/comment/font_weight" = 700

# Deletions
[deletions]
keys = [
	"/style/scrollbar.thumb.background",
	"/style/syntax/constant.builtin",
	"/style/syntax/constant.character",
	"/style/syntax/embedded",
	"/style/syntax/enum",
	"/style/syntax/escape",
	"/style/syntax/function.builtin",
	"/style/syntax/function.definition",
	"/style/syntax/function.special",
	"/style/syntax/function.special.definition",
	"/style/syntax/hint",
	"/style/syntax/label",
	"/style/syntax/lifetime",
	"/style/syntax/link_text",
	"/style/syntax/link_uri",
	"/style/syntax/predictive",
	"/style/syntax/preproc",
	"/style/syntax/primary",
	"/style/syntax/property.json_key",
	"/style/syntax/punctuation.special.symbol",
	"/style/syntax/string.doc",
	"/style/syntax/type.builtin",
	"/style/syntax/type.interface",
	"/style/syntax/type.super",
	"/style/syntax/variable.member",
	"/style/syntax/variable.parameter",
	"/style/syntax/variant",
	"/style/title_bar.inactive_background"
]
