# Reverse Generation Tool Version 3.0
name = "VSCode Dark Auto"
theme = "dark"

# Theme Colors
[color]
black = "#1E1E1E"
cornflowerblue = "#569CD6"
darkgray = "#A0A0A0"
darkslategray = "#2D2D2D"
darkslategray4 = "#3E3E3E"
darkslategray5 = "#252526"
lightgray = "#D4D4D4"
lightskyblue = "#9CDCFE"
mediumaquamarine = "#4EC9B0"

[background]
bottombar = "#333"
panel = "@darkslategray5"
primary = "@black.."
secondary = "@darkslategray5"
tabbar = "@darkslategray5"
terminal = "@black"
toolbar = "@darkslategray"
topbar = "#333"

[border]
primary = "@darkslategray4"
secondary = "#2A2A2A"

[button]
active = "#505050"
disabled = "#3C3C3C"
selected = "#4A4A4A"

[cursor]
background = "#4E4E4E40"
hover = "@darkslategray4"
line = "@darkslategray"
match = "#4A4A4A"
primary = "#FFF"
search = "#515C6A"
spaces = "#303030"

[element]
active = "@darkslategray4"
disabled = "@darkslategray"
hover = "#2A2A2A"
selected = "#37373D"

[foreground]
ignored = "@darkgray"
inactive = "@darkgray"
line = "#5A5A5A"
placeholder = "#808080"
primary = "@lightgray"
secondary = "@darkgray"

[scheme]
black = "@black"
black2 = "@darkslategray5"
blue = "@cornflowerblue"
blue2 = "#64B5F6"
cyan = "@mediumaquamarine"
cyan2 = "#4DD0E1"
green = "#6A9955"
green2 = "#8BC34A"
primary = "@cornflowerblue"
purple = "#C586C0"
purple2 = "#E57373"
red = "#F44747"
red2 = "#FF6B6B"
white = "@lightgray"
white2 = "#FFF"
yellow = "#D7BA7D"
yellow2 = "#FFC107"

[scrollbar]
primary = "#424242"
secondary = "@darkslategray4"

[syntax.attribute]
color = "@lightskyblue"
style = "normal"
weight = 400

[syntax.boolean]
color = "@cornflowerblue"
style = "normal"
weight = 400

# apple
[syntax.comment]
color = "#6A9955"
style = "italic"
weight = 400

[syntax.constant]
color = "@mediumaquamarine"
style = "normal"
weight = 400

[syntax.constructor]
color = "@mediumaquamarine"
style = "normal"
weight = 700

[syntax.function]
color = "#DCDCAA"
style = "normal"
weight = 400

[syntax.keyword]
color = "#C586C0"
style = "normal"
weight = 700

[syntax.member]
color = "@lightskyblue"
style = "normal"
weight = 400

[syntax.number]
color = "#B5CEA8..s=100"
style = "normal"
weight = 400

[syntax.operator]
color = "@lightgray"
style = "normal"
weight = 400

[syntax.parameter]
color = "@lightskyblue"
style = "normal"
weight = 400

[syntax.property]
color = "@lightskyblue"
style = "normal"
weight = 400

[syntax.punctuation.bracket]
color = "@lightgray"
style = "normal"
weight = 400

[syntax.punctuation.delimiter]
color = "@lightgray"
style = "normal"
weight = 400

[syntax.punctuation.list]
color = "@lightgray"
style = "normal"
weight = 400

[syntax.punctuation.primary]
color = "@lightgray"
style = "normal"
weight = 400

[syntax.punctuation.special]
color = "@lightgray"
style = "normal"
weight = 400

[syntax.special]
color = "#D7BA7D"
style = "normal"
weight = 400

[syntax.string]
color = "@lightskyblue..(h-170, s+20)"
style = "normal"
weight = 900

[syntax.tag]
color = "@cornflowerblue"
style = "normal"
weight = 700

[syntax.type]
color = "@mediumaquamarine"
style = "normal"
weight = 700

[syntax.var]
color = "@lightskyblue"
style = "normal"
weight = 400

[tabs]
active = "@black"
inactive = "@darkslategray"

# Overrides
[overrides]

# Deletions
[deletions]
keys = [
	"/style/syntax/function.definition",
	"/style/syntax/function.method"
]
