name = "Yue Sun"
theme = "light"

[colors]
color1 = "#BCA88F"
color2 = "#D6893C"
color3 = "#518C7B"
color4 = "#DCD7CF"
color5 = "#55818F"
color6 = "#EBE4DC"
color7 = "#FCF6ED"
color8 = "#C14B77"
color9 = "#DCD6CF"
color10 = "#CCC6BF"
color11 = "#3C3C3C"
color12 = "#6BBBCF"

[background]
secondary = "$colors.color6"
primary = "$colors.color7"
bottombar = "$colors.color9"
topbar = "$colors.color9"
toolbar = "$colors.color7"
tabbar = "$colors.color9"
panel = "$colors.color6"
terminal = "$colors.color7"

[border]
primary = "$colors.color9"
secondary = "$colors.color10"

[button]
primary = "#e5dfd6"
selected = "#e5dfd6"

[cursor]
hover = "#e5dfd6"
search = "$colors.color3..90"
line = "$colors.color1..19"
primary = "$colors.color3"
background = "$colors.color1..a0"

[element]
hover = "$colors.color10"
active = "#BDB8B279"
selected = "#CCC7C070"
disabled = "$colors.color1..19"

[foreground]
primary = "#403E3C"
secondary = "#736F6C"
placeholder = "#807974"
inactive = "#80797490"
line = "#668074"
hint = "#969696ff"
ignored = "#82827d80"

[scheme]
primary = "$colors.color3"
black = "$colors.color11"
red = "#cc7158"
green = "#699058"
yellow = "$colors.color2"
blue = "$colors.color5"
purple = "#915d8b"
cyan = "$colors.color3"
white = "#6B6B69"
white2 = "#6B6B69"
red2 = "#ff657f"
blue2 = "$colors.color12"
yellow2 = "#ffd5a3"

[scrollbar]
primary = "#dcd3c690"
secondary = "$colors.color10"

[syntax.boolean]
color = "$colors.color3"

[syntax.comment]
color = "#616161"

[syntax.constant]
color = "$colors.color3"

[syntax.constructor]
color = "$colors.color5"

[syntax.function]
color = "#699058"

[syntax.keyword]
color = "#915d8b"

[syntax.number]
color = "#635ab7"

[syntax.operator]
color = "#cc7158"

[syntax.punctuation.bracket]
color = "$colors.color8"

[syntax.punctuation.delimiter]
color = "$colors.color8"

[syntax.punctuation.list]
color = "$colors.color8"

[syntax.punctuation.primary]
color = "$colors.color8"

[syntax.punctuation.special]
color = "$colors.color8"

[syntax.special]
color = "$colors.color5"

[syntax.string]
color = "$colors.color2"

[syntax.tag]
color = "$colors.color5"

[syntax.type]
color = "$colors.color5"

[syntax.var]
color = "$colors.color11"

[tabs]
inactive = "$colors.color6"
active = "$colors.color7"
