name = "Yue Newmoon"
theme = "dark"
override = "$colors.color4"
text = "$colors.color7"

[colors]
color1 = "#120C10"
color2 = "#E6AEDC"
color3 = "#1a1218"
color4 = "#080507"
color5 = "#f9bef0"
color6 = "#000000"
color7 = "#F0E4EE"
color8 = "#998A97"
color9 = "#fff5c2"
color10 = "#1A1218"
color11 = "#dfdfdf"
color12 = "#ff91a6"
color13 = "#e2ffcc"
color14 = "#B6C6FF"
color15 = "#ceffff"
color16 = "#d5ffff"
color17 = "#ffb7e0"

[background]
secondary = "$colors.color3..f9"
bottombar = "$colors.color1"
topbar = "$colors.color1"
toolbar = "$colors.color4"
tabbar = "$colors.color1"
panel = "$colors.color10"
primary = "$colors.color4"
terminal = "$colors.color4"

[border]
primary = "$colors.color1"
secondary = "$colors.color2..30"

[button]
primary = "$colors.color5..33"
active = "$colors.color5..13"
selected = "$colors.color6"

[cursor]
hover = "$colors.color5..13"
search = "$colors.color9..40"
line = "$colors.color2..19"

[element]
hover = "$colors.color5..23"
active = "#4A3747"
selected = "$colors.color5..13"

[foreground]
primary = "$colors.color7"
secondary = "$colors.color8"
placeholder = "$colors.color8"
inactive = "$colors.color2..40"
line = "#fff5c1"
hint = "#969696ff"
ignored = "#4F3D4D"

[scheme]
primary = "$colors.color9"
black = "$colors.color6"
black2 = "$colors.color11..50"
red = "$colors.color12"
red2 = "$colors.color12"
green = "$colors.color13"
yellow = "$colors.color9"
yellow2 = "$colors.color9"
blue = "$colors.color14"
purple = "$colors.color5"
cyan = "$colors.color15"
white = "$colors.color11"
blue2 = "$colors.color3..f9"

[scrollbar]
primary = "$colors.color2..20"
secondary = "#3a2c37"

[syntax.attribute]
color = false
style = false
weight = false

[syntax.boolean]
color = "$colors.color15"

[syntax.builtin]
color = false
style = false
weight = false

[syntax.comment]
color = "#7a7a7a"

[syntax.constant]
color = "$colors.color15"

[syntax.constructor]
color = "$colors.color16"

[syntax.definition]
color = false
style = false
weight = false

[syntax.function]
color = "$colors.color13"

[syntax.keyword]
color = "$colors.color5"

[syntax.member]
color = false
style = false
weight = false

[syntax.method]
color = false
style = false
weight = false

[syntax.number]
color = "#ddccff"

[syntax.operator]
color = "#ffd8c7"

[syntax.parameter]
color = false
style = false
weight = false

[syntax.property]
color = false
style = false
weight = false

[syntax.punctuation.bracket]
color = "$colors.color17"

[syntax.punctuation.delimiter]
color = "$colors.color17"

[syntax.punctuation.list]
color = "$colors.color17"

[syntax.punctuation.primary]
color = "$colors.color17"

[syntax.punctuation.special]
color = "$colors.color17"
style = false
weight = false

[syntax.special]
color = false
style = false
weight = false

[syntax.string]
color = "$colors.color9"

[syntax.tag]
color = "$colors.color16"

[syntax.type]
color = "$colors.color16"
style = false
weight = false

[syntax.var]
color = "$colors.color11"

[tabs]
inactive = "$colors.color10"
active = "$colors.color4"

[overrides]
"border.focused" = false
"border.selected" = "$colors.color2..40"
"border.transparent" = "$colors.color2..40"
"border.disabled" = "$colors.color2..40"
"surface.background" = "$colors.color3..f9"
"drop_target.background" = "$colors.color5..23"
"text" = "$colors.color7"
"scrollbar.track.background" = "$colors.color6..00"
"scrollbar.track.border" = "$colors.color2..40"
"editor.subheader.background" = "$colors.color5..33"
"editor.highlighted_line.background" = false
"editor.wrap_guide" = "$colors.color5..33"
"editor.active_wrap_guide" = "$colors.color5..33"
"terminal.foreground" = "$colors.color11"
"terminal.bright_foreground" = false
"terminal.dim_foreground" = false
"terminal.ansi.dim_black" = false
"terminal.ansi.dim_red" = false
"link_text.hover" = false
"conflict" = false
"conflict.background" = false
"conflict.border" = false
"error.background" = "$colors.color3..f9"
"hint.border" = "$colors.color14"
"info.border" = "$colors.color14"
"modified.background" = false
"modified.border" = false
"success" = false
"warning.background" = "$colors.color3..f9"
"syntax.hint.color" = false
"syntax.hint.font_style" = false
"syntax.link_text.color" = false
"syntax.link_uri.color" = false
"syntax.primary.color" = false
"syntax.punctuation.special.symbol.color" = false
"syntax.string.escape.color" = "$colors.color15"
"syntax.text.literal.color" = "$colors.color9"
"syntax.type.interface.color" = false
"syntax.type.super.color" = false
"syntax.variable.special.color" = "$colors.color16"
"syntax.variable.special.font_style" = false
"syntax.variable.special.font_weight" = false
