name = "Yue Sun"
theme = "light"
override = "#FAF4EB"
text = "$colors.color6"

[colors]
color1 = "#DCD6CF"
color2 = "#CCC6BF"
color3 = "#ebe4dc"
color4 = "#e5dfd6"
color5 = "#BCA88F"
color6 = "#403E3C"
color7 = "#807974"
color8 = "#518C7B"
color9 = "#FCF6ED"
color10 = "#EBE4DC"
color11 = "#3C3C3C"
color12 = "#cc7158"
color13 = "#699058"
color14 = "#d6893c"
color15 = "#55818F"
color16 = "#915d8b"
color17 = "#6B6B69"
color18 = "#c14b77"
color19 = "#DCD7CF"

[background]
secondary = "$colors.color3"
bottombar = "$colors.color1"
topbar = "$colors.color1"
toolbar = "$colors.color9"
tabbar = "$colors.color1"
panel = "$colors.color10"
primary = "$colors.color9"
terminal = "$colors.color9"

[border]
primary = "$colors.color1"
secondary = "$colors.color2"

[button]
primary = "$colors.color4"
selected = "$colors.color4"

[cursor]
hover = "$colors.color4"
search = "$colors.color8..90"
line = "$colors.color5..19"

[element]
hover = "$colors.color2"
active = "#BDB8B279"
selected = "#CCC7C070"
disabled = "$colors.color5..19"

[foreground]
primary = "$colors.color6"
secondary = "#736F6C"
placeholder = "$colors.color7"
inactive = "$colors.color7..90"
line = "#668074"
hint = "#969696ff"
ignored = "#82827d80"

[scheme]
primary = "$colors.color8"
black = "$colors.color11"
red = "$colors.color12"
green = "$colors.color13"
yellow = "$colors.color14"
blue = "$colors.color15"
purple = "$colors.color16"
cyan = "$colors.color8"
white = "$colors.color17"
white2 = "$colors.color17"
red2 = "#ff657f"
blue2 = "#6BBBCF"
yellow2 = "#ffd5a3"

[scrollbar]
primary = "#dcd3c690"
secondary = "$colors.color2"

[syntax.attribute]
color = false
style = false
weight = false

[syntax.boolean]
color = "$colors.color8"

[syntax.builtin]
color = false
style = false
weight = false

[syntax.comment]
color = "#616161"

[syntax.constant]
color = "$colors.color8"

[syntax.constructor]
color = "$colors.color15"

[syntax.definition]
color = false
style = false
weight = false

[syntax.function]
color = "$colors.color13"

[syntax.keyword]
color = "$colors.color16"

[syntax.member]
color = false
style = false
weight = false

[syntax.method]
color = false
style = false
weight = false

[syntax.number]
color = "#635ab7"

[syntax.operator]
color = "$colors.color12"

[syntax.parameter]
color = false
style = false
weight = false

[syntax.property]
color = false
style = false
weight = false

[syntax.punctuation.bracket]
color = "$colors.color18"

[syntax.punctuation.delimiter]
color = "$colors.color18"

[syntax.punctuation.list]
color = "$colors.color18"

[syntax.punctuation.primary]
color = "$colors.color18"

[syntax.punctuation.special]
color = "$colors.color18"
style = false
weight = false

[syntax.special]
color = false
style = false
weight = false

[syntax.string]
color = "$colors.color14"

[syntax.tag]
color = "$colors.color15"

[syntax.type]
color = "$colors.color15"
style = false
weight = false

[syntax.var]
color = "$colors.color11"

[tabs]
inactive = "$colors.color10"
active = "$colors.color9"

[overrides]
"border.focused" = false
"border.selected" = "$colors.color19"
"border.transparent" = "$colors.color19"
"border.disabled" = "$colors.color19"
"surface.background" = "$colors.color3"
"drop_target.background" = "$colors.color19"
"text" = "$colors.color6"
"scrollbar.track.background" = "#F2ECE300"
"editor.subheader.background" = "#F0EADF"
"editor.highlighted_line.background" = false
"editor.wrap_guide" = "$colors.color5..19"
"editor.active_wrap_guide" = "$colors.color5..19"
"terminal.foreground" = "$colors.color11"
"terminal.bright_foreground" = false
"terminal.dim_foreground" = false
"link_text.hover" = false
"conflict" = false
"deleted" = false
"error" = "#cf1f4c"
"success" = false
"syntax.hint.color" = false
"syntax.hint.font_style" = false
"syntax.link_text.color" = false
"syntax.link_uri.color" = false
"syntax.primary.color" = false
"syntax.punctuation.special.symbol.color" = false
"syntax.string.escape.color" = "$colors.color8"
"syntax.text.literal.color" = "$colors.color14"
"syntax.type.interface.color" = false
"syntax.type.super.color" = false
"syntax.variable.special.color" = "$colors.color15"
"syntax.variable.special.font_style" = false
"syntax.variable.special.font_weight" = false
