name = "Yue Moon"
theme = "dark"
override = "$colors.color4"
text = "$colors.color6"

[colors]
color1 = "#1F1F1F"
color2 = "#E6CFB8"
color3 = "#252525"
color4 = "#2B2B2B"
color5 = "#3C3C3C"
color6 = "#FFEDD9"
color7 = "#A89D8F"
color8 = "#B3EFE5"
color9 = "#F277A1"
color10 = "#929292"
color11 = "#FF5370"
color12 = "#B0D89C"
color13 = "#F1BF8E"
color14 = "#8EAAF9"
color15 = "#99CBCA"
color16 = "#FFFFFF"

[background]
secondary = "$colors.color3"
bottombar = "$colors.color1"
topbar = "$colors.color1"
toolbar = "$colors.color4"
tabbar = "$colors.color1"
panel = "$colors.color3"
primary = "$colors.color4"
terminal = "$colors.color4"

[border]
primary = "$colors.color1"
secondary = "$colors.color2..20"

[button]
primary = "$colors.color3"
active = "$colors.color5..7F"
selected = "$colors.color3"

[cursor]
hover = "$colors.color3"
search = "$colors.color9..c0"
line = "$colors.color5..7F"

[element]
hover = "$colors.color2..20"
selected = "$colors.color2..10"

[foreground]
primary = "$colors.color6"
secondary = "$colors.color7"
inactive = "$colors.color2..75"
line = "#B7F5EB"
hint = "#969696ff"

[scheme]
primary = "$colors.color8"
black = "#141414"
black2 = "$colors.color10"
red = "$colors.color11"
green = "$colors.color12"
yellow = "$colors.color13"
blue = "$colors.color14"
purple = "$colors.color9"
cyan = "$colors.color15"
white = "$colors.color16"
red2 = "$colors.color11"
blue2 = "$colors.color14"
yellow2 = "$colors.color13"

[scrollbar]
primary = "$colors.color2..25"
secondary = "#45433f"

[syntax.attribute]
color = false
style = false
weight = false

[syntax.boolean]
color = "$colors.color8"

[syntax.builtin]
color = false
style = false
weight = false

[syntax.comment]
color = "$colors.color10"

[syntax.constant]
color = "$colors.color8"

[syntax.constructor]
color = "$colors.color15"

[syntax.definition]
color = false
style = false
weight = false

[syntax.function]
color = "$colors.color12"

[syntax.keyword]
color = "#BB84B4"

[syntax.member]
color = false
style = false
weight = false

[syntax.method]
color = false
style = false
weight = false

[syntax.number]
color = "#9D8FF2"

[syntax.operator]
color = "#F69385"

[syntax.parameter]
color = false
style = false
weight = false

[syntax.property]
color = false
style = false
weight = false

[syntax.punctuation.bracket]
color = "$colors.color9"

[syntax.punctuation.delimiter]
color = "$colors.color9"

[syntax.punctuation.list]
color = "$colors.color9"

[syntax.punctuation.primary]
color = "$colors.color9"

[syntax.punctuation.special]
color = "$colors.color9"
style = false
weight = false

[syntax.special]
color = false
style = false
weight = false

[syntax.string]
color = "$colors.color13"

[syntax.tag]
color = "$colors.color15"

[syntax.type]
color = "$colors.color15"
style = false
weight = false

[syntax.var]
color = "$colors.color16"

[tabs]
inactive = "$colors.color3"
active = "$colors.color4"

[overrides]
"border.focused" = false
"border.selected" = "$colors.color5..7F"
"border.transparent" = "$colors.color5..7F"
"border.disabled" = "$colors.color5..7F"
"surface.background" = "$colors.color3"
"text" = "$colors.color6"
"scrollbar.track.background" = "$colors.color4"
"scrollbar.track.border" = "$colors.color2..20"
"editor.subheader.background" = false
"editor.highlighted_line.background" = false
"editor.line_number" = "$colors.color7"
"editor.wrap_guide" = "$colors.color5..7F"
"editor.active_wrap_guide" = "$colors.color5..7F"
"terminal.foreground" = "$colors.color16"
"terminal.bright_foreground" = false
"terminal.dim_foreground" = false
"terminal.ansi.dim_black" = false
"link_text.hover" = false
"conflict" = false
"success" = false
"syntax.hint.color" = false
"syntax.hint.font_style" = false
"syntax.link_text.color" = false
"syntax.link_uri.color" = false
"syntax.primary.color" = false
"syntax.punctuation.special.symbol.color" = false
"syntax.string.escape.color" = "$colors.color8"
"syntax.text.literal.color" = "$colors.color13"
"syntax.type.interface.color" = false
"syntax.type.super.color" = false
"syntax.variable.special.color" = "$colors.color15"
"syntax.variable.special.font_style" = false
"syntax.variable.special.font_weight" = false
