name = "Theme Name"
theme = "dark"
primary = "#ff0000"

[border]
primary = "#ff0000"
secondary = "#00ff00"
selected = "$border.primary"
scrollbar = "#ff0000"
wrap = "#ff0000"

[background]
primary = "#ff0000"
secondary = "#00ff00"
gutter = "$background.primary"
surface = "$background.secondary"
drop_target = "#00000000"
panel = "#ff0000"

[background.bars]
bottombar = "#ff0000"
topbar = "#ff0000"
toolbar = "#ff0000"
tabbar = "#ff00ff"
scrollbar = "#ff0000"

[button]
primary = "#ff0000"
active = "#00ff00"
selected = "#00ff00"
disabled = "#888888"

[element]
primary = "#ff0000"
hover = "#00ff00"
active = "#00ff00"
selected = "#00ff00"
disabled = "#888888"

[foreground]
primary = "#ff0000"
hover = "#00ff00"
placeholder = "#888888"
inactive = "#888888"
line = "#ff0000"
link = "$primary"

[cursor]
primary = "#ff0000"
background = "#00ff00"
selection = "$cursor.background"
search = "#ff0000"
line = "#ff0000"
highlighted = "$cursor.line"
spaces = "#ff0000"
match = "#ff0000"

[scheme]
comment = "#ff0000"
black = "#ff0000"
black2 = "#00ff00"
red = "#ff0000"
red2 = "#00ff00"
green = "#ff0000"
green2 = "#00ff00"
yellow = "#ff0000"
yellow2 = "#00ff00"
blue = "#ff0000"
blue2 = "#00ff00"
pink = "#ff0000"
pink2 = "#00ff00"
cyan = "#ff0000"
cyan2 = "#00ff00"
white = "#ff0000"
white2 = "#00ff00"


[syntax.attribute]
color = "#ff0000"
style = false
weight = false

[syntax.boolean]
color = "#ff0000"
style = false
weight = false

[syntax.constant]
color = "#ff0000"
style = false
weight = false

[syntax.builtin]
color = "#ff0000"
style = false
weight = false

[syntax.function]
color = "#ff0000"
style = false
weight = 800

[syntax.method]
color = "$syntax.function.color"
style = "$syntax.function.style"
weight = "$syntax.function.weight"

[syntax.special]
color = "#ff0000"
style = false
weight = false

[syntax.keyword]
color = "#ff0000"
style = false
weight = 800

[syntax.number]
color = "#ff0000"
style = false
weight = false

[syntax.operator]
color = "#ff0000"
style = false
weight = false

[syntax.parameter]
color = "#ff0000"
style = false
weight = false

[syntax.property]
color = "#ff0000"
style = false
weight = false

[syntax.punctuation]
color = "#ff0000"
style = false
weight = false

[syntax.punctuation.bracket]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.delimiter]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.list]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.special]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.symbol]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.string]
color = "#ff0000"
style = false
weight = false

[syntax.string.escape]
color = "$syntax.string.color"
style = "$syntax.string.style"
weight = "$syntax.string.weight"

[syntax.type]
color = "#ff0000"
style = false
weight = 800

[syntax.type.builtin]
color = "$syntax.builtin.color"
style = "$syntax.builtin.style"
weight = "$syntax.builtin.weight"

[syntax.type.super]
color = "$syntax.special.color"
style = "$syntax.special.style"
weight = "$syntax.special.weight"

[syntax.variable]
color = "#ff0000"
style = false
weight = false
