name = "Midnight Coder"
theme = "dark"
primary = "$colors.color1"

[colors]
color1 = "#61AFEF"
color2 = "#ABB2BF"
color3 = "#56B6C2"
color4 = "#528BFF"
color5 = "#98C379"
color6 = "#E5C07B"
color7 = "#D19A66"
color8 = "#3E4451"
color9 = "#21252B"
color10 = "#E06C75"
color11 = "#BE5046"

[background]
secondary = "$colors.color9"
surface = "$colors.color9"
primary = "#282C34"
drop_target = "$colors.color8..80"
gutter = "#282C34"

[background.bars]
bottombar = "$colors.color9"
toolbar = "#282C34"

[background.bars.topbar]
active = "$colors.color9"
inactive = "$colors.color9"

[border]
primary = "$colors.color8"
secondary = "#C678DD90"
selected = "$colors.color8"

[button]
primary = "$colors.color1"
active = "$colors.color3"
selected = "$colors.color5"
disabled = "#5C6370"

[code.error]
foreground = "$colors.color10"
background = "$colors.color11"
border = "$colors.color11"

[code.hint]
foreground = "$colors.color1"
background = "$colors.color4"
border = "$colors.color4"

[code.info]
foreground = "$colors.color1"
background = "$colors.color4"
border = "$colors.color4"

[code.success]
foreground = "#C678DD"
background = "#7A9F60"
border = "#7A9F60"

[code.warning]
foreground = "$colors.color6"
background = "$colors.color7"
border = "$colors.color7"

[cursor]
search = "$colors.color6..a0"
line = "#2C313A"
highlighted = "$colors.color4..50"
spaces = "#3B4048"

[element]
primary = "$colors.color2..00"
hover = "$colors.color1..90"
active = "$colors.color3..80"
selected = "$colors.color5..80"
disabled = "#5C6370"

[foreground]
hover = "$colors.color1..80"
primary = "$colors.color2"
secondary = "$colors.color2..90"
placeholder = "#5C6370"
inactive = "#4B5263"
read = "$colors.color4..50"
write = "$colors.color4..50"
link = "$colors.color1"

[foreground.linenumber]
inactive = "#4B5263"
active = "#C678DD"

[git.conflict]
foreground = "$colors.color10"
background = "$colors.color11"
border = "$colors.color11"

[git.created]
foreground = "$colors.color5"
background = "#7A9F60"
border = "#7A9F60"

[git.deleted]
foreground = "$colors.color10"
background = "$colors.color11"
border = "$colors.color11"

[git.modified]
foreground = "$colors.color6"
background = "$colors.color7"
border = "$colors.color7"

[git.renamed]
foreground = "#C678DD"
background = "#B57EDC"
border = "#B57EDC"

[icon]
accent = "$colors.color1"

[pane]
focused = "$colors.color8"

[panel]
background = "#2C313A"
focused = "$colors.color8"

[players.1]
cursor = "$colors.color1"
background = "$colors.color4..50"
selection = "$colors.color4..50"

[scrollbar]
primary = "#4B526390"
secondary = "#C678DD90"
track = "#4B526300"

[syntax.attribute]
color = "$colors.color6"

[syntax.boolean]
color = "$colors.color7"

[syntax.builtin]
color = "$colors.color6"
weight = 800

[syntax.comment]
color = "#5C6370"

[syntax.constant]
color = "$colors.color7"

[syntax.constant.builtin]
color = "$colors.color6"

[syntax.constant.character]
color = "$colors.color3"

[syntax.definition]
color = "$colors.color1"
weight = 800

[syntax.doc]
color = "#5C6370"

[syntax.enum]
color = "$colors.color3"

[syntax.function]
color = "$colors.color1"
weight = 800

[syntax.json_key]
color = "$colors.color10"

[syntax.keyword]
color = "#C678DD"
style = "italic"
weight = 500

[syntax.lifetime]
color = "$colors.color3"

[syntax.link]
color = "$colors.color1"

[syntax.method]
color = "$colors.color1"
weight = 800

[syntax.number]
color = "$colors.color7"

[syntax.operator]
color = "$colors.color3"

[syntax.primary]
color = "$colors.color1"

[syntax.property]
color = "$colors.color10"

[syntax.punctuation]
color = "$colors.color2"

[syntax.punctuation.bracket]
color = "$colors.color2"

[syntax.punctuation.delimiter]
color = "$colors.color2"

[syntax.punctuation.list]
color = "$colors.color2"

[syntax.punctuation.special]
color = "$colors.color2"

[syntax.punctuation.symbol]
color = "$colors.color2"

[syntax.special]
color = "$colors.color3"
weight = 800

[syntax.string]
color = "$colors.color5"

[syntax.string.doc]
color = "$colors.color5"

[syntax.string.escape]
color = "$colors.color5"

[syntax.string.regex]
color = "$colors.color5"

[syntax.string.special]
color = "$colors.color5"

[syntax.string.symbol]
color = "$colors.color5"

[syntax.type]
color = "$colors.color6"
weight = 800

[syntax.type.builtin]
color = "$colors.color6"

[syntax.type.interface]
color = "$colors.color6"
weight = 800

[syntax.type.super]
color = "$colors.color3"

[syntax.variable]
color = "$colors.color10"

[syntax.variable.member]
color = "$colors.color10"

[syntax.variable.parameter]
color = "$colors.color2"

[syntax.variable.special]
color = "$colors.color3"

[tabs]
background = "$colors.color9"
inactive = "$colors.color9"
active = "#282C34"

[terminal]
background = "#282C34"
foreground = "$colors.color2"
bright_foreground = "$colors.color2"
dim_foreground = "$colors.color2"
black = "#282C34"
bright_black = "$colors.color8"
dim_black = "$colors.color8"
red = "$colors.color10"
bright_red = "$colors.color11"
dim_red = "$colors.color11"
green = "$colors.color5"
bright_green = "#7A9F60"
dim_green = "#7A9F60"
yellow = "$colors.color6"
bright_yellow = "$colors.color7"
dim_yellow = "$colors.color7"
blue = "$colors.color1"
bright_blue = "$colors.color4"
dim_blue = "$colors.color4"
cyan = "$colors.color3"
bright_cyan = "#3C909B"
dim_cyan = "#3C909B"
white = "$colors.color2"
bright_white = "#5C6370"
dim_white = "#5C6370"

[overrides]
"style.syntax.[function.special.definition].color" = "$colors.color3"
"style.syntax.lifetime.font_weight" = false
"style.syntax.[type.super].font_weight" = false
"style.syntax.[variable.special].font_weight" = false
"style.syntax.[type.builtin].font_weight" = false
"style.[scrollbar.thumb.hover_background]" = "#4B526300"
