# Reverse Generation Tool Version 3.0
name = "name"
theme = "$theme"

# Theme Colors
[color]
black = "#1B2024"
burlywood = "#DBBC7F"
cadetblue = "#5A93A2"
darksalmon = "#E69875"
darkseagreen2 = "#A7C080"
darkseagreen3 = "#83C092"
darkseagreen4 = "#98C379"
darkslategray = "#272E33"
darkslategray10 = "#2D353B"
darkslategray11 = "#343F44"
darkslategray12 = "#3D484D"
darkslategray16 = "#232A2E"
darkslategray18 = "#333C43"
darkslategray19 = "#293136"
darkslategray2 = "#2E383C"
darkslategray20 = "#3A464C"
darkslategray3 = "#374145"
darkslategray6 = "#495156"
darkslategray7 = "#21272B"
dimgray2 = "#4F585E"
dimgray3 = "#4D5960"
dimgray6 = "#555F66"
gray = "#7F897D"
gray2 = "#859289"
gray3 = "#7A8478"
indianred = "#DA6362"
lightcoral = "#E67E80"
lightgray = "#E0D8C9"
lightpink = "#EAA6A8"
lightsteelblue = "#9FC9C3"
mediumaquamarine = "#7FBBB3"
plum = "#D699B6"
silver = "#D3C6AA"
silver2 = "#BDCEA1"
silver3 = "#A5CEAE"
thistle = "#E0BACC"
wheat = "#E2CDA5"

[editor.guides.indent]
colors = "$editor.guides.indent.colors | []"
