name = "Mariana Sublime Auto"
theme = "dark"

[colors]
color1 = "#EF5266"
color2 = "#8CC592"
color3 = "#FDAB5E"
color4 = "#568FBC"
color5 = "#F9AE58"
color6 = "#2F3841"

[background]
secondary = "#22262a"
primary = "$colors.color6"
bottombar = "#2e3238"
topbar = "#2e3238"
toolbar = "$colors.color6"
tabbar = "#4e565e"
panel = "#21262a"
terminal = "$colors.color6"

[border]
primary = "#4e565e"
secondary = "#2e3842"

[button]
active = "#505050"
selected = "#4A4A4A"
disabled = "#3C3C3C"

[cursor]
hover = "#3E3E3E"
search = "#fac76190"
line = "#45525d"
spaces = "#3d464f"
match = "#5fb4b440"
primary = "$colors.color5"
background = "#4d5864"

[element]
hover = "#2A2A2A"
active = "#3E3E3E"
selected = "#383f46"
disabled = "#2D2D2D"

[foreground]
primary = "#d2d9e4"
secondary = "#78808a"
placeholder = "#8a8c8e"
inactive = "#78808a"
line = "#b9c0cb"
ignored = "#78808a"

[scheme]
primary = "$colors.color5"
black = "#1E1E1E"
black2 = "#252526"
red = "$colors.color1"
red2 = "$colors.color1"
green = "$colors.color2"
green2 = "$colors.color2"
yellow = "$colors.color3"
yellow2 = "$colors.color3"
blue = "$colors.color4"
blue2 = "$colors.color4"
purple = "#c98fc2"
purple2 = "#c98fc2"
cyan = "#43b0ae"
cyan2 = "#42a6a4"
white = "#d2d9e3"
white2 = "#d2d9e3"

[scrollbar]
primary = "#687076"
secondary = "#434c54"

[syntax.attribute]
color = "#9CDCFE"
style = "normal"
weight = 500

[syntax.boolean]
color = "$colors.color1"
style = "italic"
weight = 500

[syntax.builtin]
color = "$colors.color1"
style = "italic"
weight = 500

[syntax.comment]
color = "#999fab"
style = "normal"
weight = 500

[syntax.constant]
color = "#4EC9B0"
style = "normal"
weight = 500

[syntax.constructor]
color = "#43b0ae"
style = "normal"
weight = 500

[syntax.function]
color = "$colors.color4"
style = "normal"
weight = 500

[syntax.keyword]
color = "#c98fc2"
style = "italic"
weight = 500

[syntax.number]
color = "$colors.color3"
style = "normal"
weight = 500

[syntax.operator]
color = "#f7705a"
style = "normal"
weight = 500

[syntax.punctuation.delimiter]
color = "#9ba3af"
style = "normal"
weight = 500

[syntax.punctuation.list]
color = "#a2a9b6"
style = "normal"
weight = 500

[syntax.punctuation.primary]
color = "#f2f3f3"
style = "normal"
weight = 500

[syntax.punctuation.special]
color = "#3f8c8e"
style = "normal"
weight = 500

[syntax.special]
color = "$colors.color5"
style = "normal"
weight = 500

[syntax.string]
color = "$colors.color2"
style = "normal"
weight = 500

[syntax.tag]
color = "$colors.color1"
style = "normal"
weight = 500

[syntax.type]
color = "#43b0ae"
style = "normal"
weight = 500

[tabs]
inactive = "#4f565e"
active = "$colors.color6"

[deletions]
keys = [
	"style.syntax.[function.method]", 
	"style.syntax.[function.definition]"
]
