name = "Mariana Auto Test"
theme = "dark"

[border]
primary = "#4e565e"
secondary = "#2e3842"

[background]
primary = "#2f3841"
secondary = "#22262a"
bars = "#2e3238"
toolbar = "#2f3841"
panel = "#21262a"
terminal = "#2f3841"

[button]
hover = "#3E3E3E"
active = "#505050"
selected = "#4A4A4A"
disabled = "#3C3C3C"

[element]
hover = "#2A2A2A"
active = "#3E3E3E"
selected = "#383f46"
disabled = "#2D2D2D"

[foreground]
primary = "#d2d9e4"
dimmed = "#78808a"
placeholder = "#8a8c8e"
line = "#b9c0cb"

[scheme]
primary = "#f9ae58"
black = "#1E1E1E"
black2 = "#252526"
red = "#ef5266"
red2 = "#ef5266"
green = "#8cc592"
green2 = "#8cc592"
yellow = "#fdab5e"
yellow2 = "#fdab5e"
blue = "#568fbc"
blue2 = "#568fbc"
purple = "#c98fc2"
purple2 = "#c98fc2"
cyan = "#43b0ae"
cyan2 = "#42a6a4"
white = "#d2d9e3"
white2 = "#d2d9e3"

[tabs]
background = "#4e565e"
inactive = "#4f565e"
active = "#2f3841"

[cursor]
search = "#fac76190"
line = "#45525d"
spaces = "#3d464f"
match = "#5fb4b440"
primary = "$scheme.primary"
background = "#4d5864"

[scrollbar]
primary = "#687076"
secondary = "#434c54"

hint = "$foreground.dimmed"

[syntax]
[syntax.attribute]
color = "#9CDCFE"
style = "normal"
weight = 500

[syntax.boolean]
color = "$scheme.red"
style = "italic"
weight = 500

[syntax.comment]
color = "#999fab"
style = "normal"
weight = 500

[syntax.constant]
color = "#4EC9B0"
style = "normal"
weight = 500

[syntax.constructor]
color = "$scheme.cyan"
style = "normal"
weight = 500

[syntax.special]
color = "$scheme.primary"
style = "normal"
weight = 500

[syntax.function]
color = "$scheme.blue"
style = "normal"
weight = 500

[syntax.keyword]
color = "$scheme.purple"
style = "italic"
weight = 500

[syntax.number]
color = "$scheme.yellow"
style = "normal"
weight = 500

[syntax.operator]
color = "#f7705a"
style = "normal"
weight = 500

# [syntax.property]
# color = "N/A"
# style = "normal"
# weight = 500

[syntax.punctuation]
[syntax.punctuation.primary]
color = "#f2f3f3"
style = "normal"
weight = 500

# [syntax.punctuation.bracket]
# color = "#D4D4D4"
# style = "normal"
# weight = 500

[syntax.punctuation.delimiter]
color = "#9ba3af"
style = "normal"
weight = 500

[syntax.punctuation.list]
color = "#a2a9b6"
style = "normal"
weight = 500

[syntax.punctuation.special]
color = "#3f8c8e"
style = "normal"
weight = 500

[syntax.string]
color = "$scheme.green"
style = "normal"
weight = 500

[syntax.tag]
color = "$scheme.red"
style = "normal"
weight = 500

[syntax.type]
color = "$scheme.cyan"
style = "normal"
weight = 500

[syntax.builtin]
color = "$scheme.red"
style = "italic"
weight = 500

# [syntax.var]
# color = "#9CDCFE"
# style = "normal"
# weight = 500

# [syntax.member]
# color = "#9CDCFE"
# style = "normal"
# weight = 500

# [syntax.parameter]
# color = "#9CDCFE"
# style = "normal"
# weight = 500
