# Reverse Generation Tool Version 3.0
apple = "@red"
banana = 2
light_apple = "#FF8080"
named_angels = "named"
pear = "@red"
transparent = "@red..00"
a = 1
b = 2
c = 3

# Theme Colors
[color]
red = "#FF0000"

# Overrides
[overrides]
"angels/gabriel" = false
"apple" = "@red"
"fruits" = { grapes = ["#8000FF", { a = "@red" }] }
"list/2" = 3
"number" = 4
"pear_or_grape" = "#FF008840"

# Deletions
[deletions]
keys = [
	"/a_real_evil_dooer_mwahahha",
	"/angels/evil.dooer"
]
