name = "Quiet Light"
theme = "light"
primary = "#4B69C6"

[colors]
white = "#F5F5F5"
black = "#333333"
light_grey = "#AAAAAA"
sonic_silver_grey = "#777777"
regant_grey = "#8190A0"
la_palma_green = "#448C27"
indigo_blue = "#4B69C6"
light_cobalt_blue = "#91B3E0"
studio_purple = "#7A3E9D"
afghan_tan = "#9C5D27"
sweet_brown = "#AA3731"
lonestar_brown = "#660000"

[background]
primary = "$colors.white"
secondary = "#F3F3F3"
panel = "#F1F0F2"
gutter = "$background.primary"
terminal = "$background.primary"
code = "$background.primary"
drop_target = "#C9D0D988"

[background.bars]
bottombar = "#a690ce"
topbar = "#c4b7d7"
toolbar = "$background.bars.tabbar.active"
scrollbar_thumb = "#bbbbbbc0"
scrollbar = "$background.primary"

[background.bars.tabbar]
background = "#EEEBF2"
inactive = "#E9E6ED"
# inactive = "$background.bars.tabbar.background"
active = "$background.primary"

[border]
primary = "#9769dc00"
secondary = "#E9E6ED"
selected = "$border.primary"
scrollbar = "$border.primary"

[button]
primary = "$primary..20"
hover = "#ff0000"
active = "$primary..40"
selected = "#4A4A4A"
disabled = "#3C3C3C"

[element]
hover = "#e0e0e0"
active = "$primary..50"
selected = "#d2dbcd"
disabled = "#f07D99"

[cursor]
primary = "#54494B"
background = "#C9D0D980"
selection = "#C9D0D9a0"
search = "#edc9d899"
line = "#E4F6D4"
highlighted = "#e4eaed"
spaces = "#AAAAAA"
match = "#c0d1e0"

[players.2]
cursor = "#197F8C"
background = "#A1DAE6"
selection = "#A1DAE670"

[foreground]
hover = "#E8F1FAe0"
primary = "#333333"
secondary = "#737373"
placeholder = "$foreground.secondary..90"
inactive = "$foreground.secondary..70"
link = "$primary"

[foreground.linenumber]
inactive = "#6D705B"
active = "$primary"

[scheme]
black = "#000000"
black2 = "#666666"
# black3 = "$scheme.black"
red = "#AA3731"
red2 = "#cd3131"
# red3 = "$scheme.red"
green = "#0f7c10"
green2 = "#12ce14"
# green3 = "$scheme.green"
yellow = "#949800"
yellow2 = "#b5ba01"
# yellow3 = "$scheme.yellow"
blue = "#0551a5"
blue2 = "#4B69C6"
# blue3 = "$scheme.blue"
magenta = "#bc06bc"
magenta2 = "#D94CD9"
# magenta3 = "#FBACFB"
cyan = "#0798bc"
cyan2 = "#7AB9CC"
# cyan3 = "$scheme.cyan"
white = "#555555"
white2 = "#a5a5a5"
# white3 = "$scheme.white"

[code.error]
foreground = "#B3655E"
background = "#ffeaea"
border = "#f1897f"

[code.info]
foreground = "#3D96B3"
background = "#f2fcff"
border = "#4ec1e5"

[code.hint]
foreground = "#808080c0"
background = "$code.info.background"
border = "$code.info.border"

[code.warning]
foreground = "#B39D3C"
background = "#fffee2"
border = "#ffe055"

[git.created]
foreground = "$scheme.green"
background = "$scheme.green2"
border = "$scheme.green"

[git.ignored]
foreground = "$foreground.secondary..90"

[git.modified]
foreground = "$colors.indigo_blue"

[syntax.attribute]
color = "$colors.regant_grey"
style = "italic"

[syntax.boolean]
color = "$colors.afghan_tan"
style = "normal"

[syntax.builtin]
style = "normal"

[syntax.comment]
color = "$colors.light_grey"
style = "italic"

[syntax.constant]
color = "$colors.studio_purple"
style = "normal"

[syntax.constructor]
color = "#ff0000"
style = "normal"

[syntax.escape]
color = "#777777"
style = "normal"

[syntax.function]
color = "$colors.sweet_brown"
style = "normal"
weight = 700

[syntax.hint]
color = "$code.hint.foreground"
style = "italic"

[syntax.keyword]
color = "$colors.indigo_blue"
style = "normal"

[syntax.method]
# color = "$colorso"
style = "normal"

[syntax.number]
color = "$colors.afghan_tan"
style = "normal"

[syntax.operator]
color = "$colors.sonic_silver_grey"
style = "normal"

[syntax.primary]
color = "$primary"

[syntax.property]
color = "$colors.studio_purple"
style = "normal"

[syntax.punctuation]
color = "$colors.sonic_silver_grey"
style = "normal"

[syntax.punctuation.bracket]
color = "$colors.black"
style = "normal"
weight = 400

[syntax.punctuation.delimiter]
style = "normal"

[syntax.punctuation.list]
style = "normal"

[syntax.punctuation.special]
style = "normal"

[syntax.punctuation.symbol]
style = "normal"

[syntax.special]
color = "$primary"
style = "normal"
weight = 700

[syntax.string]
color = "$colors.la_palma_green"
style = "normal"

[syntax.string.regex]
color = "$colors.indigo_blue"
style = "normal"

[syntax.string.special]
style = "normal"

[syntax.tag]
color = "$colors.indigo_blue"
style = "normal"

[syntax.type]
color = "$colors.studio_purple"
style = "normal"
weight = 700

[syntax.variable]
color = "$colors.studio_purple"
style = "normal"

[syntax.variable.parameter]
style = "normal"

[syntax.variable.special]
# color = "$colors.color11"
style = "normal"
