id = "aquarium-theme"
name = "Aquarium Theme"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Aquarium theme for Zed"
repository = "https://github.com/biaqat/aquarium-theme-zed"