name = "Aquarium Light"
theme = "light"
primary = "#788697"
hint = "#2c2d3e20"

[foreground]
primary = "#708192"
editor = "#525F6B"
secondary = "#63718b"
ignored = "#63718b90"
hint = "#9f9eac"
inactive = "#d5d4e0"
placeholder = "#788697"
line = "#50546d"

[background]
primary = "#e6e6f1"
secondary = "#d5d4e0"
topbar = "#d7d7e2"
bottombar = "#d7d7e2"
toolbar = "#d5d4e000"
panel = "#d7d7e2"
terminal = "#e6e6f1"

[border]
primary = "#70819160"
secondary = "#70819160"

[button]
primary = "#cccbd990"
hover = "#9ca6b9"
active = "#7f8e9d40"
selected = "#303047"
disabled = "#fC3C3C"

[element]
primary = "#292c3e00"
hover = "#63718b30"
active = "#7f8e9d40"
selected = "#9ca6b990"
disabled = "#fD2D2D"

[tabs]
background = "#d7d7e2"
inactive = "#e1e1ec"
active = "#e6e6f1"

[cursor]
primary = "$primary..e0"
background = "#d5d4e0"
search = "#e8cca780"
line = "#d5d4e0"
spaces = "#d5d4e0"
match = "$scheme.black..50"

[scrollbar]
primary = "#d5d4e0e0"
secondary = "#1a1a2400"

[scheme]
primary = "$scheme.cyan"
black = "#9ca6b9"
black2 = "#9ca6b9"
red = "#c34864"
red2 = "$background.secondary"
green = "#7d9685"
green2 = "$background.secondary"
yellow = "#de956f"
yellow2 = "$background.secondary"
blue = "#6a8cbc"
blue2 = "$background.secondary"
purple = "#8787bf"
purple2 = "$background.secondary"
cyan = "#829fb0"
cyan2 = "$background.secondary"
white = "#708191"
white2 = "#708191"

[syntax.attribute]
color = "#6a8cbc"
style = "normal"

[syntax.boolean]
color = "$scheme.blue"
style = "normal"

[syntax.comment]
color = "#9ca6b9"
style = "italic"

[syntax.constant]
color = "#d66652"
style = "normal"

[syntax.constructor]
color = "$scheme.white2"
style = "normal"

[syntax.special]
color = "#d66652"
style = "normal"

[syntax.function]
color = "$scheme.cyan"
style = "italic"

[syntax.keyword]
color = "$scheme.red"
style = "italic"

[syntax.number]
color = "#d66652"
style = "normal"

[syntax.operator]
# color = "#63718b"
color = "$scheme.red"
style = "normal"

[syntax.property]
color = "$scheme.purple"
style = "normal"

[syntax.punctuation.primary]
color = "#708191"
style = "normal"

[syntax.punctuation.bracket]
color = "$syntax.punctuation.primary.color"
style = "normal"

[syntax.punctuation.delimiter]
color = "$syntax.punctuation.primary.color"
style = "normal"

[syntax.punctuation.list]
color = "$syntax.punctuation.primary.color"
style = "normal"

[syntax.punctuation.special]
color = "#8787bf"
style = "normal"

[syntax.string]
color = "$scheme.green"
style = "normal"

[syntax.tag]
color = "$scheme.purple"
style = "normal"

[syntax.method]
color = "$scheme.yellow"
style = "normal"

[syntax.type]
color = "$scheme.yellow"
style = "italic"

[syntax.var]
color = "$scheme.purple"
style = "normal"

[syntax.member]
color = "#6a8cbc"
style = "normal"

[syntax.parameter]
color = "#6a8cbc"
style = "normal"

[syntax.builtin]
color = "$scheme.yellow"
style = "italic"
