name = "Polar"
theme = "light"
primary = "#8bb3c2"

[border]
primary = "#eceff4"
secondary = "#eceff4"
# secondary = "#FFF"

[foreground]
primary = "#434c5e"
secondary = "$foreground.primary..b0"
ignored = "$foreground.primary..43"
hint = "$scheme.blue..90"
inactive = "#d8dee9"
placeholder = "#d8dee9b3"
line = "$foreground.primary"

[background]
primary = "#ffffff"
secondary = "#ffffff"
bottombar = "#eceff4"
topbar = "$background.primary"
toolbar = "$background.primary"
panel = "$background.primary"
terminal = "$background.primary"

[button]
primary = "$background.bottombar"
hover = "$background.bottombar"
active = "#d8dee990"
selected = "#4A4A4A"
disabled = "#3C3C3C"

[element]
primary = false
hover = "$primary..40"
active = "$primary"
selected = "#e6e9ef"
disabled = false

[scheme]
primary = "$primary"
black = "#eceff4"
black2 = "#d8dee9"
red = "#bf616a"
red2 = "#D99399"
green = "#a3be8c"
green2 = "#a3be8c"
yellow = "#ebcb8b"
yellow2 = "#ebcb8b"
blue = "#81a1c1"
blue2 = "#81a1c1"
purple = "#b48ead"
purple2 = "#b48ead"
cyan = "#88c0d0"
cyan2 = "#8fbcbb"
white = "#6C717D"
white2 = "#2e3440"

[tabs]
background = "$background.primary"
inactive = "$background.primary"
active = "$background.secondary"

[cursor]
primary = "$foreground.primary"
background = "#eaecf1"
search = "$scheme.cyan..66"
line = "#edeff3"
spaces = "#dfe2eb"
match = "#e5eef2"

[scrollbar]
primary = "#e5e9f099"
secondary = "$background.primary"

[syntax.attribute]
color = "$scheme.cyan2"
style = "normal"


[syntax.boolean]
color = "$scheme.blue"
style = "normal"


[syntax.comment]
color = "#aeb9ce"
style = "normal"


[syntax.constant]
color = false
style = "normal"


[syntax.constructor]
color = "$scheme.blue"
style = "normal"


[syntax.special]
color = "$scheme.yellow"
style = "normal"


[syntax.function]
color = "$scheme.cyan"
style = "normal"


[syntax.keyword]
color = "$scheme.blue"
style = "normal"


[syntax.number]
color = "$scheme.purple"
style = "normal"


[syntax.operator]
color = "$scheme.blue"
style = "normal"


[syntax.property]
color = "$foreground.primary"
style = "normal"


[syntax.punctuation.primary]
color = "$foreground.primary"
style = "normal"


[syntax.punctuation.bracket]
color = "$syntax.punctuation.primary.color"
style = "normal"


[syntax.punctuation.delimiter]
color = "$scheme.blue"
style = "normal"


[syntax.punctuation.list]
color = "#D4D4D4"
style = "normal"


[syntax.punctuation.special]
color = "$scheme.blue"
style = "normal"


[syntax.string]
color = "$scheme.green"
style = "normal"


[syntax.tag]
color = "$scheme.blue"
style = "normal"


[syntax.type]
color = "$scheme.cyan2"
style = "normal"


[syntax.var]
color = false
style = "normal"


[syntax.member]
color = false
style = "normal"


[syntax.parameter]
color = false
style = "normal"
