name = "default-temaplte"
theme = "dark"
primary = "#569CD6"

[foreground]
primary = "#D4D4D4"
secondary = "#D4D4D4"
ignored = "#808080"
hint = "#808080"
inactive = "#A0A0A0"
placeholder = "#808080"
line = "#5A5A5A"

[background]
primary = "#1E1E1E"
secondary = "#252526"
topbar = "#2D2D2D"
bottombar = "#2D2D2D"
tabbar = "#2D2D2D"
toolbar = "#2D2D2D"
panel = "#252526"
terminal = "#1E1E1E"

[border]
primary = "#3E3E3E"
secondary = "#2A2A2A"

[tabs]
inactive = "#2D2D2D"
active = "#1E1E1E"

[cursor]
primary = "#FFFFFF"
background = "#4e4e4e40"
search = "#515C6A"
line = "#2D2D2D"
spaces = "#303030"
match = "#4A4A4A"
hover = "#3E3E3E"

[scrollbar]
primary = "#424242"
secondary = "#3E3E3E"

[button]
primary = "#569CD6"
active = "#505050"
selected = "#4A4A4A"
disabled = "#3C3C3C"

[element]
primary = false
hover = "#2A2A2A"
active = "#3E3E3E"
selected = "#37373D"
disabled = "#2D2D2D"

[scheme]
primary = "#569CD6"
black = "#1E1E1E"
black2 = "#252526"
red = "#F44747"
red2 = "#FF6B6B"
green = "#6A9955"
green2 = "#8BC34A"
yellow = "#D7BA7D"
yellow2 = "#FFC107"
blue = "#569CD6"
blue2 = "#64B5F6"
purple = "#C586C0"
purple2 = "#E57373"
cyan = "#4EC9B0"
cyan2 = "#4DD0E1"
white = "#D4D4D4"
white2 = "#FFFFFF"

[syntax.attribute]
color = "#9CDCFE"
style = "normal"

[syntax.boolean]
color = "#569CD6"
style = "normal"

[syntax.comment]
color = "#6A9955"
style = "italic"

[syntax.constant]
color = "#4EC9B0"
style = "normal"

[syntax.constructor]
color = "#4EC9B0"
style = "normal"

[syntax.definition]
color = "#DCDCAA"
style = "normal"

[syntax.special]
color = "#D7BA7D"
style = "normal"

[syntax.function]
color = "#DCDCAA"
style = "normal"

[syntax.keyword]
color = "#C586C0"
style = "normal"

[syntax.method]
color = "#DCDCAA"
style = "normal"

[syntax.number]
color = "#B5CEA8"
style = "normal"

[syntax.operator]
color = "#D4D4D4"
style = "normal"

[syntax.property]
color = "#9CDCFE"
style = "normal"

[syntax.punctuation.primary]
color = "#D4D4D4"
style = "normal"

[syntax.punctuation.bracket]
color = "#D4D4D4"
style = "normal"

[syntax.punctuation.delimiter]
color = "#D4D4D4"
style = "normal"

[syntax.punctuation.list]
color = "#D4D4D4"
style = "normal"

[syntax.punctuation.special]
color = "#D4D4D4"
style = "normal"

[syntax.string]
color = "#CE9178"
style = "normal"

[syntax.tag]
color = "#569CD6"
style = "normal"

[syntax.type]
color = "#4EC9B0"
style = "normal"

[syntax.var]
color = "#9CDCFE"
style = "normal"

[syntax.member]
color = "#9CDCFE"
style = "normal"

[syntax.parameter]
color = "#9CDCFE"
style = "normal"

[syntax.builtin]
color = "#4EC9B0"
style = "italic"
