name = "Aylin Selene"
theme = "dark"
primary = "$colors.aubergine"
z = "#00000000"

[colors]
white = '#ffffff'
l_white = '#ebefff'
d_white = '#c8c8db'
yt = "#e0e2eb"
gray_light = '#74778c'
gray = '#606375'
midgray = "#363C4A"
gray_dark = '#535560'
semigray = "#42444b"
lighterblack = "#303F54"
lightblack = '#202938'
semiblack = '#262f3e'
black = '#1f2430'
midblack = '#1B202B'
blacker = '#171B25'
aubergine = '#FD98B9'
marzipan = '#ecc48d'
orange = '#EB8378'
turquoise = '#7fdbca'
sky_2 = '#9fd4ff'
sky = '#6cbeff'
sap = '#ebff00'
purple = '#c792ea'
pink = '#f45c7f'
green = '#addb67'

[border]
primary = "#363C4A"
secondary = "$border.primary"
selected = "$border.primary"
scrollbar = "$colors.black"
wrap = "$colors.gray"

[background]
primary = "$colors.black"
secondary = "$colors.blacker"
gutter = "$background.primary"
surface = "$background.secondary"
drop_target = "$colors.gray..80"
panel = "$colors.midblack"
code = "$colors.midblack"

[background.bars]
bottombar = "$colors.blacker"
topbar = "$colors.blacker"
toolbar = "$background.primary"
tabbar = "$colors.blacker"
scrollbar = "$z"
scrollbar_thumb = "#36465E90"

[tabs]
background = "$background.bars.tabbar"
active = "$background.primary"
inactive = "$colors.midblack"

[button]
primary = "$colors.blacker"
active = "$colors.midblack"
selected = "$colors.sky"
disabled = "$colors.gray_dark"

[element]
primary = "$z"
hover = "$colors.lightblack"
active = "$colors.semiblack"
selected = "$colors.gray..80"
disabled = "$colors.gray_dark"

[foreground]
primary = "$colors.l_white"
secondary = "$colors.d_white..e0"
hover = "$colors.jeans_blue..80"
placeholder = "$colors.gray_light"
inactive = "$colors.gray"
link = "$primary"
accent = "$colors.sky"
hint = "$colors.gray_light..a0"

[foreground.linenumber]
active = "$primary"
inactive = "$colors.lighterblack"

[cursor]
primary = "$primary"
background = "$colors.lighterblack..90"
selection = "$cursor.background"
search = "#ffdf8850"
line = "#242f3f"
highlighted = "$cursor.selection"
spaces = "#3B4048"
match = "$colors.gray_light..50"

[scheme]
comment = "#6f738a"
black = "$colors.blacker"
black2 = "$colors.semiblack"
red = "$colors.orange"
red2 = "#b86c66"
green = "$colors.green"
green2 = "#82a256"
yellow = "$colors.marzipan"
yellow2 = "#b99c76"
blue = "$colors.sky"
blue2 = "#538dbf"
pink = "$colors.purple"
pink2 = "#8869a5"
cyan = "$colors.turquoise"
cyan2 = "#5b9891"
white = "$colors.l_white"
white2 = "#9fa3b2"

[syntax.comment]
style = "italic"

[syntax.attribute]
color = "$colors.d_white"
style = false
weight = false

[syntax.boolean]
color = "$colors.aubergine"
style = false
weight = false

[syntax.constant]
color = "$colors.marzipan"
style = false
weight = 700

[syntax.builtin]
color = "$colors.aubergine"
style = false
weight = 500

[syntax.function]
color = "$colors.turquoise"
style = false
weight = false

[syntax.method]
color = "$syntax.function.color"
style = "$syntax.function.style"
weight = "$syntax.function.weight"

[syntax.special]
color = "$colors.turquoise"
style = false
weight = false

[syntax.keyword]
color = "$colors.sky"
style = false
weight = false

[syntax.number]
color = "$colors.aubergine"
style = false
weight = false

[syntax.operator]
color = "$colors.aubergine"
style = false
weight = false

[syntax.parameter]
color = "$colors.purple"
style = false
weight = false

[syntax.property]
color = false
style = false
weight = false

[syntax.punctuation]
color = "$colors.yt"
style = false
weight = false

[syntax.punctuation.bracket]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.delimiter]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.list]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.special]
color = "$colors.aubergine"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.punctuation.symbol]
color = "$syntax.punctuation.color"
style = "$syntax.punctuation.style"
weight = "$syntax.punctuation.weight"

[syntax.string]
color = "$colors.marzipan"
style = false
weight = false

[syntax.string.escape]
color = "$colors.aubergine"
style = "$syntax.string.style"
weight = "$syntax.string.weight"

[syntax.tag]
color = "$colors.aubergine"
style = false
weight = false

[syntax.type]
color = "$colors.d_white"
style = false
weight = false

[syntax.type.builtin]
color = "$syntax.builtin.color"
style = "$syntax.builtin.style"
weight = "$syntax.builtin.weight"

[syntax.type.super]
color = "$syntax.special.color"
style = "$syntax.special.style"
weight = "$syntax.special.weight"

[syntax.variable]
color = false
style = false
weight = false
