name = "Yue Fullmoon Lite Test"
theme = "dark"
primary = "$colors.color1..df"

[colors]
color1 = "#FF89B2"
color2 = "#AFA0FF"
color3 = "#1D212E"
color4 = "#282D3B"
color5 = "#AEE1E0"
color6 = "#A1B1E6"
color7 = "#FFD5A3"
color8 = "#FF657F"
color9 = "#181C26"
color10 = "#414963"
color11 = "#DFE0F2"
color12 = "#C7EFB2"
color13 = "#CCFFFF"

[backgroud]
secondary = "$colors.color3"

[background]
primary = "$colors.color4"
bottombar = "$colors.color9"
toolbar = "$colors.color4"
panel = "$colors.color3"
gutter = "$colors.color4"
secondary = "$colors.color3"

[background.topbar]
active = "$colors.color9"

[border]
primary = "$colors.color9"
secondary = "$colors.color6..25"

[button]
primary = "$colors.color3"
selected = "$colors.color3"

[code.error]
foreground = "$colors.color8"
background = "#FF5370a0"
border = "$colors.color8"

[code.hint]
foreground = "#6D7694ff"
background = "$colors.color2..a0"
border = "$colors.color2"

[code.info]
foreground = "$colors.color2"
background = "$colors.color2..a0"
border = "$colors.color2"

[code.warning]
foreground = "$colors.color7"
background = "#ffd39cb0"
border = "#CFA879"

[cursor]
search = "$colors.color2..90"
line = "$colors.color10..7F"
highlighted = "$colors.color10"
match = "$colors.color10"

[element]
hover = "#414860"
active = "$colors.color6..15"
selected = "$colors.color6..25"

[foregorund]
ignored = "#6D7694"

[foreground]
hover = "$colors.color3"
primary = "#D9E1FF"
secondary = "#8F95A8"
placeholder = "#717B99"
inactive = "#717B99"

[foreground.linenumber]
inactive = "#7a7b91"
active = "$colors.color1"

[git.created]
foreground = "$colors.color12"

[git.deleted]
foreground = "$colors.color8"
background = "$colors.color8"
border = "$colors.color8"

[git.modified]
foreground = "$colors.color7"

[players.0]
cursor = "$colors.color1..df"
background = "#00000000"
selection = "$colors.color1..3f"

[scrollbar]
primary = "$colors.color6..25"
track = "$colors.color4"
secondary = "$colors.color6..25"

[syntax.boolean]
color = "$colors.color13"

[syntax.comment]
color = "#7a7b91"

[syntax.constant]
color = "$colors.color13"

[syntax.constructor]
color = "$colors.color5"

[syntax.function]
color = "$colors.color12"

[syntax.keyword]
color = "#cc94c5"

[syntax.number]
color = "$colors.color2"

[syntax.operator]
color = "#ffa697"

[syntax.punctuation]
color = "$colors.color1"

[syntax.punctuation.bracket]
color = "$colors.color1"

[syntax.punctuation.delimiter]
color = "$colors.color1"

[syntax.punctuation.list]
color = "$colors.color1"

[syntax.punctuation.special]
color = "$colors.color1"

[syntax.special]
color = "$colors.color7"

[syntax.string]
color = "$colors.color7"

[syntax.string.escape]
color = "$colors.color13"

[syntax.tag]
color = "$colors.color5"

[syntax.type]
color = "$colors.color5"

[syntax.variable]
color = "$colors.color11"

[tabs]
background = "$colors.color9"
inactive = "$colors.color3"
active = "$colors.color4"

[terminal]
background = "$colors.color4"
foreground = "$colors.color11"
black = "$colors.color10"
red = "$colors.color1"
green = "$colors.color12"
yellow = "$colors.color7"
blue = "$colors.color2"
magenta = "#cc94c5"
cyan = "$colors.color5"
white = "$colors.color11"

[overrides]
"style.[scrollbar.thumb.border]" = false
"style.syntax.[variable.special].color" = "$colors.color5"
