name = "(TEST) Yue Newmoon NEW"
theme = "dark"
primary = "#FFF1A6"

[colors]

[background]
secondary = "#1a1218"
surface = "#1a1218f9"
primary = "#0D090D"
drop_target = "#f9bef023"
panel = "#1A1218"
gutter = "#0D090D"
terminal = "#0D090D"

[background.bars]
bottombar = "#120C10"
topbar = "#120C10"
toolbar = "#0D090D"
scrollbar_thumb = "#E6AEDC20"
scrollbar = "#00000000"

[background.bars.tabbar]
background = "#120C10"
inactive = "#1A1218"
active = "#0D090D"

[border]
primary = "#120c10"
secondary = "#3a2c37"
selected = "#E6AEDC40"
transparent = "#E6AEDC40"
disabled = "#E6AEDC40"
scrollbar = "#3a2c37"

[button]
primary = "#f9bef033"
active = "#f9bef013"
selected = "#000000"

[code.error]
foreground = "#ff91a6"
background = "#1a1218f9"
border = "#ff91a6"

[code.info]
foreground = "#969696ff"
background = "#1a1218f9"
border = "#B6C6FF"

[code.warning]
foreground = "#FFF1A6"
background = "#1a1218f9"
border = "#FFF1A6"

[cursor]
search = "#FFF1A63a"
line = "#F9A2EC23"
primary = "#FFF1A6"
background = "#00000000"
selection = "#F9A2EC33"

[element]
hover = "#f9bef023"
active = "#4A3747"
selected = "#f9bef013"

[foreground]
hover = "#f9bef013"
primary = "#F0D8EB"
secondary = "#998A97"
placeholder = "#998A97"
inactive = "#7A5674"

[foreground.linenumber]
inactive = "#7A5674"
active = "#FFF1A6"

[git.created]
foreground = "#e2ffcc"

[git.ignored]
foreground = "#4F3D4D"

[git.modified]
foreground = "#FFF1A6"

[guide]
active = "#f9bef033"

[scheme]
black = "#080508"
black2 = "#3d2b3a"
red = "#ff91a6"
red2 = "#ff91a6"
green = "#D4FFB3"
yellow = "#FFF1A6"
yellow3 = "#FFF1A6"
blue = "#B6C6FF"
magenta = "#F9A2EC"
cyan = "#BFFFFF"
white = "#B38FAB"
red3 = "#ff91a6"
blue2 = "#080508fe"
blue3 = "#B6C6FF"

[syntax.boolean]
color = "#BFFFFF"

[syntax.comment]
color = "#7A5674"

[syntax.constant]
color = "#BFFFFF"

[syntax.constructor]
color = "#BFFFFF"

[syntax.escape]
color = "#BFFFFF"

[syntax.function]
color = "#D4FFB3"

[syntax.keyword]
color = "#F9A2EC"

[syntax.number]
color = "#CCB3FF"

[syntax.operator]
color = "#FFCAB3"

[syntax.punctuation]
color = "#FFB3DE"

[syntax.punctuation.bracket]
color = "#FFB3DE"

[syntax.punctuation.delimiter]
color = "#FFB3DE"

[syntax.punctuation.list]
color = "#FFB3DE"

[syntax.punctuation.special]
color = "#FFB3DE"

[syntax.string]
color = "#FFF1A6"

[syntax.string.regex]
color = "#FFF1A6"

[syntax.string.special]
color = "#FFF1A6"

[syntax.tag]
color = "#BFFFFF"

[syntax.text]
color = "#FFF1A6"

[syntax.type]
color = "#BFFFFF"

[syntax.variable]
color = "#F0D8EB"

[syntax.variable.special]
color = "#BFFFFF"

[overrides]
"style.[border.focused]" = false
"style.[panel.focused_border]" = false
"style.[pane.focused_border]" = false
"style.[scrollbar.thumb.hover_background]" = false
"style.[terminal.bright_foreground]" = false
"style.[terminal.dim_foreground]" = false
"style.[terminal.ansi.dim_red]" = false
"style.[terminal.ansi.bright_blue]" = false
"style.[terminal.ansi.dim_blue]" = false
"style.conflict" = false
"style.[conflict.background]" = false
"style.[conflict.border]" = false
"style.[modified.border]" = false
"style.success" = false
"style.[editor.wrap_guide]" = "#F9BEF033"
"style.[editor.subheader.background]" = "#F9BEF033"
"style.[link_text.hover]" = false
"style.[scrollbar.track.border]" = "#E6AEDC40"
"style.[editor.highlighted_line.background]" = false
"style.[terminal.ansi.dim_black]" = false
