name = "Quiet Light"
theme = "light"
primary = "#3599A6"

[colors]
color1 = "#FCA4A7"
color2 = "#f2f2f2"
color3 = "#B5E7BE"
color4 = "#F7E79F"
color5 = "#C4DBFA"
color6 = "#333333"
color7 = "#00733B"
color8 = "#000000"
color9 = "#CE0505"
color10 = "#2AAACB"
color11 = "#91B3E0"
color12 = "#7A3E9D"
color13 = "#f3f3f3"
color14 = "#f5f5f5"
color15 = "#AAAAAA"
color16 = "#3E3E3E"
color17 = "#067D17"
color18 = "#B28C00"
color19 = "#7A7A7A"
color20 = "#4B69C6"

[background]
secondary = "$colors.color2"
primary = "$colors.color14"
gutter = "$colors.color14..00"

[background.bars]
bottombar = "#705697"
toolbar = "#f5f5f5"

[background.bars.topbar]
inactive = "#d6cfe2"
active = "#c4b7d7"

[border]
primary = "#d6cfe200"
secondary = "#c8c8c8"
selected = "$colors.color13"

[button]
primary = "$colors.color2"
active = "#3eb2c120"
selected = "#4A4A4A"
disabled = "#3C3C3C"

[code.error]
foreground = "$colors.color9"
background = "$colors.color1"
border = "$colors.color1"

[code.hidden]
foreground = "$colors.color19"

[code.hint]
foreground = "$colors.color19"
background = "$colors.color5"
border = "$colors.color5"

[code.info]
foreground = "#063FDB"
background = "$colors.color5"
border = "$colors.color5"

[code.success]
foreground = "$colors.color17"
background = "$colors.color3"
border = "$colors.color3"

[code.warning]
foreground = "#804ea2"
background = "$colors.color4"
border = "$colors.color4"

[cursor]
primary = "#54494B"
search = "#b8e6c7"
line = "#E4F6D4"
highlighted = "#e4eaed"
spaces = "#aaaaaa"

[element]
hover = "#eae2f8"
active = "#3EA2C140"
selected = "#D0D8DC"
disabled = "#207D99"

[foreground]
hover = "#B1C6CC"
primary = "$colors.color6"
secondary = "#4E4E4Ff0"
placeholder = "$colors.color15"
inactive = "#b6b6b6"
read = "#cdcdcd"
write = "#cdcdcd"
link = "#705698"

[foreground.linenumber]
inactive = "#6d705c"
active = "#9769dc"

[git.conflict]
foreground = "$colors.color9"
background = "$colors.color1"
border = "$colors.color1"

[git.created]
foreground = "$colors.color17"
background = "$colors.color3"
border = "$colors.color3"

[git.deleted]
foreground = "$colors.color9"
background = "$colors.color1"
border = "$colors.color1"

[git.ignored]
foreground = "#6c707e"

[git.modified]
foreground = "$colors.color18"
background = "$colors.color4"
border = "$colors.color4"

[panel]
background = "$colors.color2"

[players.1]
cursor = "#54494b"
background = "#dfe3e7"
selection = "#dfe3e7"

[scrollbar]
primary = "#bbbbbb90"
secondary = "$colors.color16..00"
track = "$colors.color16..00"

[syntax.attribute]
color = "#8190A0"
style = "italic"

[syntax.boolean]
color = "#9C5D27"
style = "normal"

[syntax.comment]
color = "$colors.color15"
style = "italic"

[syntax.doc]
color = "#AAAAAA"

[syntax.constant]
color = "#9C5D27"
style = "normal"

[syntax.constant.builtin]
style = "italic"

[syntax.constructor]
color = "#4EC9B0"
style = "normal"

[syntax.definition]
style = "normal"

[syntax.enum]
color = "$colors.color11"
style = "normal"

[syntax.function]
color = "#AA3731"
style = "normal"
weight = 700

[syntax.hint]
color = "$colors.color19"
style = "italic"

[syntax.keyword]
color = "#4B69C6"
style = "normal"

[syntax.link]
color = "$colors.color10"

[syntax.method]
color = "#AA3731"
style = "normal"

[syntax.number]
color = "#9C5D27"
style = "normal"

[syntax.operator]
color = "#777777"
style = "normal"

[syntax.primary]
color = "$colors.color10"

[syntax.property]
color = "$colors.color12"
style = "normal"

[syntax.punctuation]
color = "#777777"
style = "normal"

[syntax.punctuation.bracket]
style = "normal"

[syntax.punctuation.delimiter]
style = "normal"

[syntax.punctuation.list]
style = "normal"

[syntax.punctuation.special]
style = "normal"

[syntax.punctuation.symbol]
style = "normal"

[syntax.string]
color = "#448C27"
style = "normal"

[syntax.string.escape]
color = "#777777"

[syntax.string.regex]
color = "#4B69C6"

[syntax.string.special]
color = "#9C5D27"


[syntax.tag]
color = "#4B69C6"
style = "normal"

[syntax.type]
color = "$colors.color12"
weight = 700

[syntax.type.interface]
color = "$colors.color12"
style = "italic"

[syntax.type.super]
color = "$colors.color12"
style = "italic"

[syntax.variable]
color = "#7A3E9D"
style = "normal"

[syntax.variable.member]
style = "normal"

[syntax.variable.parameter]
style = "normal"

[syntax.variable.special]
color = "$colors.color11"
style = "normal"

[tabs]
background = "$colors.color2"
inactive = "#ececec"
active = "$background.primary"

[terminal]
background = "#f3f3f3"
foreground = "$colors.color6"
bright_foreground = "$colors.color6"
dim_foreground = "$colors.color6"
black = "$colors.color8"
bright_black = "$colors.color8"
dim_black = "$colors.color8"
red = "$colors.color9"
bright_red = "$colors.color1"
dim_red = "$colors.color1"
green = "$colors.color17"
bright_green = "$colors.color3"
dim_green = "$colors.color3"
yellow = "$colors.color18"
bright_yellow = "$colors.color4"
dim_yellow = "$colors.color4"
blue = "#063FDB"
bright_blue = "$colors.color5"
dim_blue = "$colors.color5"
magenta = "#B309B3"
bright_magenta = "#FBACFB"
dim_magenta = "#FBACFB"
cyan = "#028E8E"
bright_cyan = "#BFEEEE"
dim_cyan = "#BFEEEE"
white = "#656565"
bright_white = "#929292"
dim_white = "#929292"

# [overrides]
# "style.[editor.foreground]" = "#7b3e9d"
